### ISSUE TITLE
dl.ccbluex.net

### ISSUE THREAD

**Issue by ghost** [jspenguin2017/AdBlockProtector#1006]
### Test link (required):
http://dl.ccbluex.net/download/skip/index.php?target=0862cc031

### Screenshot of the web page (including address bar and extension icons) (required):
![image](https://user-images.githubusercontent.com/21245760/49328623-2c1e6100-f574-11e8-8c00-ee4bd7184e4f.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![image](https://user-images.githubusercontent.com/21245760/49328636-6f78cf80-f574-11e8-9b5c-b02028f259d9.png)

### Environment (Required):

- Operating System and Version: Windows 10 1803
- Browser and Version: Firefox 63.0.3
- Adblocker and Version: uBlock Origin 1.17.2

#### Your filter lists (Required):
![image](https://user-images.githubusercontent.com/21245760/49328656-a0f19b00-f574-11e8-9301-a5696309749a.png)

#### Your custom filters (Required if you have any):
![image](https://user-images.githubusercontent.com/21245760/49328651-92a37f00-f574-11e8-8e8c-d48da267602a.png)

### Add everything else that you believe to be useful below (optional):

**Comment by jspenguin2017** [comment]
Firefox tracking protection is out of scope of ND.
