### ISSUE TITLE
gaana.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#105]
> Songs stop after the first one when ad blocker is on.

https://github.com/reek/anti-adblock-killer/issues/2987

**Comment by uBlock-user** [comment]
Happens when running a playslist, the second song won't play by itself.

**Comment by ghajini** [comment]
Since no antiadblock notice is being shown,it will better fit into easylist ,I think

**Comment by uBlock-user** [comment]
It's not about anti adblock notice, it sabotages itself upon detection and limits the feature. Easylist can't do a damn thing here.

**Comment by X01X012013** [comment]
@uBlock-user I am a bit busy lately, have you tried locking the variable to `false` or `undefined`?

**Comment by ghajini** [comment]
`@@||clmbtech.com^$script,domain=gaana.com`
will do the job...
but whitelisting is not the solution.....so any script injecting filters or cosmetic filter

**Comment by uBlock-user** [comment]
`clmbtech.com` is not a working domain, and can be used for other nefarious purposes, please don't post such solutions here, they will always always third-party servers and drill more holes.

**Comment by uBlock-user** [comment]
@X01X012013 Yes, I did, didn't have any effect.

**Comment by X01X012013** [comment]
White-listing a non-existent domain fixes it? What?! Has anyone pinned down the offending function yet?

**Comment by uBlock-user** [comment]
It doesn't fix it, more like it breaks the script and that filter pulls other third party crap too.

**Comment by ghajini** [comment]
that nonexistent `clmbtech` just fixed problem..sorry...i will investigate further...

**Comment by uBlock-user** [comment]
Sure then use that, it's not a fix, more of a compromise, besides,  the functionlity itself looks broken rather. Only happens on playlist when auto-played, but you can still play the audio manually.

**Comment by uBlock-user** [comment]
@X01X012013 You may add that filter and close the issue if you're satisfied.

**Comment by ghajini** [comment]
no i don't mean that....wait we will find workaround

**Comment by uBlock-user** [comment]
Btw here's the script if you're interested i solving this puzzle - http://css375.gaanacdn.com/min/?b=js&f=dfp-v1.js,googlepluslogin.js,adsserving_preroll.js,share.js,pageSectionTracking.js,download_sync.js,ga_social_tracking.js,columbia.js,browserclose.js,aes.js,phonelogin.js&version=341.17&341.17

**Comment by X01X012013** [comment]
Ah I see why. `static.clmbtech.com` is a working domain, but not `clmbtech.com` itself. 
Can you try this rule? 
```JavaScript
let url = "http://example.com/index.php?url=http://static.clmbtech.com/ad/commons/js/colombia_v2.js";
if(a.doc.location.protocol === "https:"){
    url = url.replace(/http/g, "https");
}
a.$(`<script src="${url}"></script>`).appendTo("html");
```

**Comment by uBlock-user** [comment]
Does that requires `static.clmbtech.com` to be whitelisted for it to work ?

**Comment by X01X012013** [comment]
@uBlock-user Yea, that rule doesn't actually work. Maybe we can find more useful information in their autoplay code...

**Comment by uBlock-user** [comment]
- Only happens when the scripted auto-play.

- If you manually play the first track, then the second track will load on completion of the first track.

**Comment by X01X012013** [comment]
Or they are trying to insert audio ads between tracks? Like Google Home?

**Comment by uBlock-user** [comment]
No, nothing like that because that would be in English, right ?

**Comment by uBlock-user** [comment]
Whitelisting all scripts from `clmbtech.com` inserts **ad hyperlinks** in the page - 

![](https://i.gyazo.com/2a0f0f5b23bbcf88bc13d3256454981f.png)

This is why I never whitelist third-party connections.

**Comment by ghajini** [comment]
`@@||clmbtech.com^$script,domain=gaana.com`
`gaana.com##[data-cb$="colombiaTextAds"]`

**Comment by X01X012013** [comment]
@ghajini That is not ideal, but if we can't find another solution, we might have to use that for now... I'll see if we can find another way.

**Comment by uBlock-user** [comment]
If you're going to use that then be ready to swat any popups, text ads and hyperlinks as you have no control what third-party shit is being inserted on daily basis.

**Comment by X01X012013** [comment]
@uBlock-user Good point... Is there a dummy script in uBO for this `colombia` thing?

**Comment by uBlock-user** [comment]
@X01X012013 Not exactly, but feel free to rummage through here - https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt

**Comment by uBlock-user** [comment]
@X01X012013 Did you find a workaround for this case ?

**Comment by jspenguin2017** [comment]
@uBlock-user This should now be properly fixed. 
```JavaScript
if (a.domCmp(["gaana.com"])) {
    const noop = function () { };
    const pType = {
        _auds: "", //all
        isauds: false,
        lotamecall: false,
        itemInfo: [],
        colombiaAdeURL: "",
        deviceType: "", //desktop
        colombiaCookies: "",
        privateMode: true,
        adIconInfo: [],
        fns: { push: noop },
        update: noop,
        colombiaAdRequest: noop,
        resetAdDivClass: noop,
        clear: noop,
        clearData: noop,
        notifyColombiaAd: noop,
        refresh: noop,
        refreshFBAd: noop,
        timeoutHandler: noop,
        load: noop,
        loadDataAd: noop,
        drawIconHtml: noop,
        loadDisplayAd: noop,
        jsonCallback: noop,
        getCB: noop,
        repllaceMacro: noop,
        getAdJSON: noop,
        fireImpression: noop,
        fireThirdPartyImp: noop,
        storeThirdPartyImprURL: noop,
        dataResponseFormat: noop,
        storeAdIcons: noop,
        checkDevice: noop,
        dfpLog: noop
    };
    const obj = function () { };
    obj.prototype = pType;
    a.readyOnly("colombia", new obj);
}
```

**Comment by uBlock-user** [comment]
@jspenguin2017 Can't test it anymore as it requires Flash Player installed.

**Comment by ghajini** [comment]
@uBlock-user In chrome flash is default...no need to install that....just check

**Comment by jspenguin2017** [comment]
@ghajini Actually, in Chrome, flash is blocked by default. But you can enable it from the padlock or sphere icon, it works on my machine.

**Comment by ghajini** [comment]
Okz...flash is like off in chrome like Firefox old days with flash.....thanx

**Comment by uBlock-user** [comment]
@ghajini I use Chromium, not chrome specifically, secondly I have uninstalled Flash Player from my device. I no longer support Flash fyi.

**Comment by jspenguin2017** [comment]
I tested on two computers, both works, I'll close this now, please let me know if something breaks.
