### ISSUE TITLE
mellow.link and related domains

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#106]
http://adz.bz/6CZi
More domains and test links: https://github.com/X01X012013/AdBlockProtector/issues/106#issuecomment-289551936

https://github.com/reek/anti-adblock-killer/issues/2992

**Comment by uBlock-user** [comment]
anti adblock script - http://adz.bz/js/linkclick?v=r-0H57G3ysMfE2G2fyvu8QHrncC9yy8_8cG1kikZgS01

**Comment by uBlock-user** [comment]
@X01X012013 It checks for `#frameAd` being and it's height more or equal to 50, looks like a CSS based bait

**Comment by uBlock-user** [comment]
Thanks, the fic works as intended.

**Comment by X01X012013** [comment]
This is fixed. @uBlock-user Thanks for that link. You still need to pass reCaptcha obviously. 
I chose to not use CSS bait, it'll be script based anyway, why not use a solution that is harder to bypass.

**Comment by ghajini** [comment]
`http://mellow.link/9owj`
related to antiadblock

**Comment by X01X012013** [comment]
@ghajini Thanks, these domains are added to the domain list.

**Comment by espamearola** [comment]
http://mellowads.com/3sQA
http://url.vin/7xI0
http://clik.bz/8lBF
More mirrors

**Comment by jspenguin2017** [comment]
Thanks, I'll have a look.

**Comment by ghajini** [comment]
Where to find mirrors of these sites........

**Comment by jspenguin2017** [comment]
@espamearola Thanks, those domains are added to Script.
