### ISSUE TITLE
televisaofutebol.com (iframe of: freetvall.com, estadiofutebol.com)

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#116]
Test links: 
http://freetvall.com/video/9kb116rwshsb/motors-tv
http://www.estadiofutebol.com/gratis/motorstv

Related issues in AAK: 
https://github.com/reek/anti-adblock-killer/issues/3029
https://github.com/reek/anti-adblock-killer/issues/3030

**Comment by X01X012013** [comment]
Could be related to cookies.

**Comment by X01X012013** [comment]
The `iframe` is very polymorphic, the `iframe` seems to redirect a couple times before landing on the actual player. Cookies are heavily used in this process. 
The website works once in 5~10 times, when it works, the final landing URL of the `iframe` is `http://www.embeducaster.com/embedplayer/motopilas/1/650/500`

**Comment by X01X012013** [comment]
At the beginning, the `iframe` with URL `http://www.televisaofutebol.com/iframe.php?chname=motorstv&height=500&width=650&autostart=true` is added to `#videoPlayer` by JS.

**Comment by X01X012013** [comment]
From time to time, it will serve the following HTML, which seems to be the "good one", other times it is redirected to `http://ww1.zuuk.net/` which contains nothing but garbage. 
```HTML
<!DOCTYPE html>
<html>
	<head>
		<META http-equiv="refresh" content="1;URL='http://zq2.zeroredirect11.com/zcredirect?visitid=8d5429b7-175d-11e7-a053-1296eec45028&type=meta'">
	</head>
	<body>
		<script type="text/javascript">
			setTimeout(function () {
				var pageWidth = window.innerWidth ? window.innerWidth : (document.documentElement && document.documentElement.clientWidth ? document.documentElement.clientWidth : document.getElementsByTagName('body')[0].clientWidth);
				var pageHeight = window.innerHeight ? window.innerHeight : (document.documentElement && document.documentElement.clientHeight ? document.documentElement.clientHeight : document.getElementsByTagName('body')[0].clientHeight);
				var iframeDetected = window.self !== window.top;
				window.location="http://zq2.zeroredirect11.com/zcredirect?visitid=8d5429b7-175d-11e7-a053-1296eec45028&type=js&browserWidth=" + pageWidth +"&browserHeight=" + pageHeight +"&iframeDetected=" + iframeDetected;
			}, 1);
		</script>
	</body>
</html>
```

**Comment by ghajini** [comment]
`zq2.zeroredirect11.com`
falls under `spyware and adware` category.... Check here 
https://virustotal.com/en/url/b556b75f070d1ba6524631a9274e5f140acf17975ff9b3cb969069755c993b4d/analysis/1491113831/

Or here

http://www.brightcloud.com/tools/url-ip-lookup.php

**Comment by uBlock-user** [comment]
It tries to load garbage and if it succeeds than the real iframe is loaded, and it expects garbage to be blocked by default.

**Comment by X01X012013** [comment]
This is the 4.4kB response I got using Insomnia: 
```HTML
<!DOCTYPE html><html data-adblockkey="MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANnylWw2vLY4hUn9w06zQKbhKBfvjFUCsdFlb6TdQhxb9RXWXuI4t31c+o8fYOv/s8q1LGPga3DE1L/tHU4LENMCAwEAAQ==_D7lG3K/yhnKrvzhjqrDGlTirOt1S/O7wvTav2xKFxkSSaxMG78kcgplYqcFKKr2VQK0HOekJCR8hHkOZVjiGsg=="><head><meta charset="utf-8" /><style type="text/css"></style><title>zuuk.net&nbsp;-&nbsp; Resources and Information.</title><link rel="shortcut icon" type="image/png" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYxIDY0LjE0MDk0OSwgMjAxMC8xMi8wNy0xMDo1NzowMSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNS4xIFdpbmRvd3MiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MzRFNEQ3NkJEMjRGMTFFMTk4RjA4NDhFNTEwRTcyMkIiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MzRFNEQ3NkNEMjRGMTFFMTk4RjA4NDhFNTEwRTcyMkIiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDozNEU0RDc2OUQyNEYxMUUxOThGMDg0OEU1MTBFNzIyQiIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDozNEU0RDc2QUQyNEYxMUUxOThGMDg0OEU1MTBFNzIyQiIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PukMAkAAAAEsUExURcbf8uXx+vb6/eXx+Q5FtN/t+Ofz+rbX7uTr9+Tq9y5fvlh+y7rY7+n0+lJ6yS1evt7l9Sxdvr/b8L3a8BRLtpev31mAy+v0+k13yLLD59Hm9PT5/c3Z8LXG6Oby+pXG5aG54vX3/Git2LvZ79bg8vr8/vP4/Mjh8+Pw+Ofy+sPd8cfj9G2P0cDc783k9Ex2x6DK5xlOuCBUumWJztDm9DZkwLTF6Ojt92yP0s7a8OPq9m6Y1d3l9cHP7OLp9kNvxNPo9Wes2DNhwJSv3uDt+Ovw+cDP6yNVuurv+Nbf8pjI5aDL56G44rTL6h1RuWaJz9bp9tDo9u31+oWi2TZlwMfg8E16yd7t99Hc8Vl+ysri897l9JCq3FB5yPL1++/2/MLQ7HGb1j9sw////2AvJ1QAAADsSURBVHjaRM9ZMwNREAXgnpvLZKOENsQSJrTlIjHEEhQZS2JJxljHmoT+//9B37w4j19Xna4DzKzGDbHKLN+MdZlB4GNJ8fV9AbH1W7ew7g6zn9ORt/uM8wJkBOs7eHai/P05Bnp0S8ynBQz2qk9v0jEbTyjpKWZRI0Z9hqlV29u9ynQmR6PAY7g0NYH+efvzYDHAQ4bExBY0Bi3E7BHDkGkI+MXN7+ncV1pKU1AhIiYbudgvx957c+t2YW2k1ugJUKmqdXs7DGdiN5+yW+hV4K4cVhI37wzGdX4u0skL9FYcRw2ANh74P38CDABMCjqJfzUcfQAAAABJRU5ErkJggg==" /><meta name="expires" content="NOW" ><meta name="description" content=" zuuk.net is your first and best source for information about zuuk . Here you will also find topics relating to issues of general interest. We hope you find what you are looking for!"><script type="text/javascript" src="http://img.sedoparking.com/js/jquery-1.4.2.min.js" ></script>
<script type="text/javascript">(function(){function a(a,b,d){a&&!c&&(c=!0,b===window.location.href&&(b="[rendered html]"),$.get("/log/jserr.php",{msg:a,file:b,line:d}),c=!1)}var c=!1;window.onerror=a;$(function(){window.onerror=a})})();</script>
</head><body class="oneclick content" data-generated="21.04.15-12:49"><div id="content"><img width="16" height="16" src="http://img.sedoparking.com/images/js_preloader.gif"/>
		<script type="text/javascript">
		var doLocRed = false;
		var jsLocRed = function() {window.location = "http://ww1.zuuk.net/search/redirect.php?f=http%3A%2F%2Fdprtb.com%2Fclick%3Fdata%3DQ05lVVdHMmpNamtBaTZ2elY2SWdwVW1talBnU3ZYT2ZISkx6TXg3cjRRLUQwOHhWME80YmxvRkRWVFA1akFybHlLaXQ4cUJNZE94MEJVOXdmRjg4aWgxQ3JKYlJIY2JaRDNCalM1Si00Rmgxc215SVZTUUlJM25ETXRvWWpmd2ZfU3BEOHVEUnJIMmdiRWh1YnZiU3J3Mg2%26id%3Deafa75e0-7c57-46c5-8b60-518b98561f94&amp;v=MzUxNGJmNWU5N2I3YTViZGU4ZjBjMDNlMDE3OWNmNmMJMQl3dzEuenV1ay5uZXQ1OGUwNzc1MDhlYWM3MC45NjQ4NDIyMgl3dzEuenV1ay5uZXQ1OGUwNzc1MDhlYjExOC43NzIzMjQ1NwkxNDkxMTA1NjE3CWFkXzM1XzA=&amp;l=NglBRFMJYWJhNDVkMDI4MDg2NWIxNjkxOTU1MjkxOTViYWVhZDQJMAkxMwkJMzEJMQkxCTAJYzRjOWRkOTcxOWQ5MzRhMjZiNjZkOGExMDczNDg4Y2IJCTIyMDc1NzEyNgljCTAJCQkxMTAxCTM1CTUJNjAJMTQ5MTEwNTYxNwk3LjMxNUUtNQlOCTAJMAkwCQkJCQkJd3cxLnp1dWsubmV0NThlMDc3NTA4ZWFjNzAuOTY0ODQyMjIJMAkJMQkxNjE3LDE2MjAJMTA2MAkxNTY0MzA4OTMJCTY2LjIyMi4xMzUuMw%3D%3D"
		}
		if(doLocRed){jsLocRed();}
		</script>
		</div>
<script type="text/javascript">
$.ajax({ url: 'http://ww1.zuuk.net/' + 's' + 'earch/tsc.php?&ses=14911056171c379fe6f40f33f12abc38c91939f33f&200=MjIwNzU3MTI2&21=NjYuMjIyLjEzNS4z&681=MTQ5MTEwNTYxNzFjMzc5ZmU2ZjQwZjMzZjEyYWJjMzhjOTE5MzlmMzNm&682=&616=&crc=2b0464753edf9f98616187c8904b5da4a10e787a&cv=1',success:jsLocRed});
</script>
</body></html>
```
There is another response that is 20.4kB, but it's quite obvious that one is pure garbage. These two responses are the only ones that I could get from Insomnia, the response above is loaded with `view-source`. 
I'm not sure what they do to "load garbage and see if it succeeds", since they are returning HTTP301 from their servers. Are they trying to redirect the user through all the garbages?

**Comment by uBlock-user** [comment]
> are they trying to redirect the user through all the garbages?

Something like that yes since all garbage is blocked on my end, the first garbage which tries to load gets blocked by uBO and I get "Requests to the server have been blocked by an extension."

**Comment by uBlock-user** [comment]
This iframe - `http://www.televisaofutebol.com/iframe.php?chname=motorstv&height=500&width=650&autostart=true` redirects you to `http://bridge.sf.admarketplace.net/ct?version=16.0.0&key=1491145860201300081.1&ci=1491145860420.11105`

**Comment by ghajini** [comment]
Can anyone confirm things by easylist here
https://forums.lanik.us/viewtopic.php?f=62&t=36682&p=117898#p117898

I don't gave windows PC ri8 now

**Comment by jspenguin2017** [comment]
@ghajini 

>The video just play fine here without any anti adblock message.

That's not the case here.

**Comment by ghajini** [comment]
Then what's issue then? Iam little confused

**Comment by jspenguin2017** [comment]
@ghajini Well, the video doesn't play, unlike what smed79 said.

**Comment by ghajini** [comment]
Regarding `estadiofutebol` that's as per okiehsch ,is fixed in ublock origin.....can anyone confirm that......if so then you can remove rules from adblock protector......

**Comment by jspenguin2017** [comment]
@ghajini I only have one rule that fixes the buttons, the website itself is not fixed. 
`@@||cdn.tvdez.com^$image,domain=www.estadiofutebol.com`

**Comment by jspenguin2017** [comment]
@ghajini 
Looks like the rule that was blocking the icons is removed, so we can remove our exception rule as well. Looks like uBO filter did fix it! Good job! We can close this issue now 😄

**Comment by jspenguin2017** [comment]
@ghajini I see that we have a couple more filters copied form AAK, they affect a few more domains, since they don't cause problems, I'll leave them there. 
![image](https://cloud.githubusercontent.com/assets/7283682/25809733/3377a270-33cb-11e7-9412-dde07d6508e4.png)

**Comment by ghajini** [comment]
Did you see this on all listed sites 
![img_20170508_202933](https://cloud.githubusercontent.com/assets/20338483/25810464/cf7eeb9e-342d-11e7-9347-b4feb6d82536.JPG)

`http://freetvall.com/video/9kb116rwshsb/motors-tv
http://www.estadiofutebol.com/gratis/motorstv`

**Comment by jspenguin2017** [comment]
Try updating all your filters. 
![image](https://cloud.githubusercontent.com/assets/7283682/25811121/6e19759e-33cf-11e7-99dc-ce500a065bd2.png)
![image](https://cloud.githubusercontent.com/assets/7283682/25811136/7dea0524-33cf-11e7-8bba-cad076293d7e.png)
