### ISSUE TITLE
NSFW! pornvibe.org

### ISSUE THREAD

**Issue by mattdx123** [jspenguin2017/AdBlockProtector#119]
I have adblock, reek's and your protector. If you know how to fix it just tell me step by step i'm a noob, lol.

**Comment by X01X012013** [comment]
Hi, please be aware that our filter does not work on AdBlock, it currently only support uBlock Origin. Also, Reek's AAK will conflict with AdBlock Protector Script. 
Looks like the only issue is the banner and popup. I'll have a look.

**Comment by uBlock-user** [comment]
I believe he's referring to openload.co's Anti Adblock which has been patched since.

**Comment by X01X012013** [comment]
Ah, ok... The banner is easy to fix:
`pornvibe.org##.special-message-content`
I'll see what I can do for the popup.

**Comment by uBlock-user** [comment]
popups are third-party, so block these domains `jzlzdnvvktcf.com` and `lskzcjgerhzn.com`

**Comment by X01X012013** [comment]
Nope... That didn't stop the popup...

**Comment by uBlock-user** [comment]
Ofcourse you will need to block popads and popcash too, assuming if you already did you won't get any popups further,.

**Comment by uBlock-user** [comment]
That should do the job

```
||$third-party,script,domain=pornvibe.org
@@||openload.co/embed^$third-party
@@||oloadcdn.net^

```

**Comment by X01X012013** [comment]
Awesome! Thanks!

**Comment by uBlock-user** [comment]
@mattdx123 some feedback would be appreciated.

**Comment by mattdx123** [comment]
Thanks for the help! Everything is fine now.

**Comment by mattdx123** [comment]
I started getting pop ups on videos again

**Comment by uBlock-user** [comment]
link ? I cannot guess or please provide the exact link where you produced popups.

**Comment by mattdx123** [comment]
It's on every video I've clicked so far, [http://pornvibe.org/yoga-instructor-anna-rose-private-class/](url) this for example

**Comment by jspenguin2017** [comment]
Still can't reproduce. @uBlock-user Can you test this? 
Openload *might* be back with new popup logic...

**Comment by uBlock-user** [comment]
@jspenguin2017 No I cannot. If @mattdx123  is still reproducing this, then it's either from the cache or a rare race condition happening on his end.

**Comment by jspenguin2017** [comment]
I still can't reproduce the popup, please make sure to update everything.
