### ISSUE TITLE
neodrive.co

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#135]
Test link: http://neodrive.co/embed/QDHS20ASC0DUDU4YDWG3J6EEQ

I came across this issue when I was porting AAK script, I'm not sure how exactly should this work. Can someone who uses this website have a look? Does our solution work?

**Comment by xxcriticxx** [comment]
page doesn't load for me

**Comment by X01X012013** [comment]
Hum... Looks like the server is down for now... I was working when I was porting AAK. 
![image](https://cloud.githubusercontent.com/assets/7283682/24715098/a2550b40-19e7-11e7-9480-cc3c4a89f032.png)
We'll test it later.

**Comment by xxcriticxx** [comment]
what was on that page that we need?

**Comment by X01X012013** [comment]
We just need to test if our solution for that domain works.

**Comment by uBlock-user** [comment]
https://isup.me/neodrive.co

It is down currently.

**Comment by uBlock-user** [comment]
Server has been down for a long time, much longer as in few months. I wonder why would you create this issue in the first place knowing the website being dead.

**Comment by xxcriticxx** [comment]
script was going there for some code probably

**Comment by X01X012013** [comment]
@uBlock-user No, it was definitely not down when I was porting AAK script 2 months ago. I has a few solutions marked as experimental, I was expecting people to open issue about them when they see the prompt, but no one did it for this domain, so I thought I should open one and properly test things out.

**Comment by uBlock-user** [comment]
Well I have tried `neodrive.co` links and they go dead everytime I tried to open them, so I never bothered to open here.

**Comment by uBlock-user** [comment]
Domain is set to expire in October and the site status is `Inactive`.

**Comment by X01X012013** [comment]
We'll wait one more month, if by the beginning of May this website is still down, I'll remove the solution.

**Comment by jspenguin2017** [comment]
Looks like they are not coming back, removing experimental solution.
