### ISSUE TITLE
Grant cross origin XHR permissions at install time

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#144]
Use `@connect` to grant cross origin XHR at install time. 
Also, update help page.

**Comment by uBlock-user** [comment]
But `// @connect *` is already present in the Script ? That should do the job as expected.

**Comment by X01X012013** [comment]
I mean grant permission on install time. `@connect *` will ask for permission as needed.

**Comment by jspenguin2017** [comment]
This is added to To-do list.
