### ISSUE TITLE
linkneverdie.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#146]
https://linkneverdie.com/

https://github.com/reek/anti-adblock-killer/issues/3081

**Comment by jspenguin2017** [comment]
This would remove the block screen, but I'm not sure where is the content hidden... 
```JavaScript
if (a.config.debugMode && a.domCmp(["linkneverdie.com"])) {
    a.readOnly("eval", function () {
        a.$("div").each(function () {
            if (this.id.length === 30) {
                this.remove();
            }
        });
    });
}
```

**Comment by uBlock-user** [comment]
So filters such as

```
linkneverdie.com#@#.adsbygoogle
linkneverdie.com##script:inject(noeval.js)
```

should work, but they don't. The block screen still appears. I will update the Script and post more feedback.

**Comment by uBlock-user** [comment]
The Script solution make the page appear white -

![](https://i.gyazo.com/057abe7242e3481bbed0e75e3902d830.png)

**Comment by uBlock-user** [comment]
I'm not sure why you're locking `eval`, this website uses the updated version of the BAB script which doesn't involve `eval`ing at all.

**Comment by uBlock-user** [comment]
Used `@@||linkneverdie.com^$elemhide` and it works for some reason wasn't working with only disabling `adsbygoogle` cosmetic filter for me. Anyways, consider this patched.

**Comment by jspenguin2017** [comment]
@uBlock-user Hum, it works on my end. This version has eval hidden in JSFuck.

**Comment by jspenguin2017** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/25064200/baf6eb3c-21b2-11e7-9f13-d5dc2eae452d.png)
![image](https://cloud.githubusercontent.com/assets/7283682/25064203/c6b1c28a-21b2-11e7-93b4-2ca69d872c8d.png)
![image](https://cloud.githubusercontent.com/assets/7283682/25064214/fc53073c-21b2-11e7-8b28-ee6a77b70711.png)

**Comment by jspenguin2017** [comment]
@uBlock-user Oh, BTW, the core code of this version of BAB is hidden in the *comments* of a function, and is extracted with `Function.prototype.toString`. Don't try to decompile it, it's packed like 5 times with different methods. When you see those weird brackets and parentheses, 99% of time it's JSFuck. 
I don't really understand what is the author of BAB thinking, no matter how many layers is his code packed, removing `eval` just breaks it all.

**Comment by jspenguin2017** [comment]
I tested it on Chrome and Opera, both works fine with only `linkneverdie.com#@#.adsbygoogle`, I'm not sure why Chromium behaves differently. 
Closing this issue now.

**Comment by uBlock-user** [comment]
Turns out it was loading the page from the cache, I removed the cache containing an hour of browsing and it worked. But still I will stick to disabling all generic elements for that one, so they cannot use another one from the Easylist.

**Comment by jspenguin2017** [comment]
They have 3 different classes on that wrapper, but white listing `.adsbygoogle` was enough in my testings. We'll see what we can do if it breaks again.
