### ISSUE TITLE
nick change?

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#147]
why?

**Comment by jspenguin2017** [comment]
For personal reasons. I'll fix all references.

**Comment by xxcriticxx** [comment]
ok dude

**Comment by jspenguin2017** [comment]
All references fixed. Script will be redirected normally, List should work as is, but I recommend you to re-install it.

**Comment by xxcriticxx** [comment]
to many systems :)

**Comment by jspenguin2017** [comment]
It should be fine if you leave them as is. I put redirect directive in List, but I'm not sure uBO will parse that.

**Comment by xxcriticxx** [comment]
ok

**Comment by jspenguin2017** [comment]
I'll do big clean ups after my finals. My systems need some serious maintenance...

**Comment by uBlock-user** [comment]
Force Update works fine, no need to re-install.

**Comment by jspenguin2017** [comment]
It should work for List too. I'm just not 100% sure.
