### ISSUE TITLE
ally.sh, al.ly

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#148]
http://ally.sh/hUgtD http://ally.sh/0eYWZ

https://github.com/reek/anti-adblock-killer/issues/3089

-----

http://al.ly/Pnsvt

https://github.com/adsbypasser/adsbypasser/issues/1379

**Comment by jspenguin2017** [comment]
Thanks to @okiehsch 
```
||p207208.clksite.com^$subdocument,redirect=noopframe,domain=ally.sh
@@||ally.sh^$generichide
```
Still need to remove countdown.

**Comment by ghajini** [comment]
Why to remove countdown......site have too many popups ,please fix asap....

**Comment by jspenguin2017** [comment]
Hum... Yea, we need to fix popups too.

**Comment by okiehsch** [comment]
`ally.sh##script:inject(popads.net.js)` is one way to fix the popups, maybe you prefer a different way,
so just a suggestion.

**Comment by uBlock-user** [comment]
Or just kill third party scripts from random domains, that will do the job too.

**Comment by MrLuckyAdBlock** [comment]
||p207208.clksite.com^$subdocument,redirect=noopframe,domain=ally.sh

Is the above line correct ?
Latest version of Adblock Plus shows "Unknown filter option" error.

**Comment by ghajini** [comment]
That will nit work with adblock plus. ...also this project "adblock protector" is known to work with ublock origin only......
So install ublock origin,ubo extra,tampermonkey with adblock protector(script and list both required)

**Comment by MrLuckyAdBlock** [comment]
Will keep current setup for now.

Thanks for info. Might come handy one day.

**Comment by uBlock-user** [comment]
Adblock Protector won't work as expected if you use GreaseMonkey though.

**Comment by jspenguin2017** [comment]
Thanks, I'll have a look.

**Comment by jspenguin2017** [comment]
Actually, AdsBypasser has a solution... Code never lie, comments sometimes do, I need to remember that next time... Turns out that domain isn't reCaptcha protected. 

From AdsBypasser: https://greasyfork.org/en/scripts/4881-adsbypasser/code
```JavaScript
$.register({
  rule: {
    host: [
      /^al\.ly$/,
      /^ally\.sh$/,
    ],
  },
  ready: function () {
    'use strict';
    $.removeNodes('iframe, #CashSlideDiv, #ct_catfish');
    var a = $('#modal-shadow');
    a.style.display = 'block';
    a = $('#modal-alert');
    a.style.left = 0;
    a.style.top = 80;
    a.style.display = 'block';
  },
});
```

**Comment by jspenguin2017** [comment]
This is fixed. Update Script and List and see if it works 😄

**Comment by uBlock-user** [comment]
I suppose we can't bypass it like we do with `adf.ly` bunch ?

**Comment by jspenguin2017** [comment]
No, it is protected by reCatpcha...

**Comment by uBlock-user** [comment]
adsbypasser list `ally.sh` in their SITES list - https://github.com/adsbypasser/adsbypasser/blob/master/SITES.md

So apparently they can bypass ?

**Comment by jspenguin2017** [comment]
@uBlock-user No, their solution doesn't work at all.

**Comment by uBlock-user** [comment]
reCaptcha must have been added later on when the webmaster found out adsbypasser was bypassing it like they do with `adf.ly` and others and the dev still doesn't know about this yet.

**Comment by jspenguin2017** [comment]
@uBlock-user Ah... That make sense... It's not always easy to dig in the history and find out what happened. Good job 😄 
I added `al.ly` to the domain list.

**Comment by jspenguin2017** [comment]
AdsBypasser updated: 
```JavaScript
$.register({
  rule: {
    host: [
      /^al\.ly$/,
      /^ally\.sh$/,
    ],
  },
  ready: function () {
    'use strict';

    // first stage
    var i = $.$('body > section > iframe');
    if (i) {
      // the site will detect iframe being removed or not
      i.src = 'about:blank';

      // wait a reasonable time to avoid AdsBlock detection
      _.wait(3000).then(function () {
        var a = $('a.redirect');
        a.click();
      });

      return;
    }

    // second stage
    i = $.searchScripts(/"href","([^"]+)"\)\.remove/);
    if (!i) {
      _.warn('site changed');
      return;
    }
    i = i[1];

    $.openLink(i);
  },
});
```

**Comment by okiehsch** [comment]
@jspenguin2017 just FYI
a now obsolete fix for `al.ly` was already part of uBO-filters, so I updated it with the following filterset.
https://github.com/uBlockOrigin/uAssets/commit/884fc16089deb8a021abf4d4bf7517d79bca1094
````
||p207208.clksite.com^$subdocument,redirect=noopframe,domain=al.ly|ally.sh
al.ly,ally.sh##script:inject(noeval.js)
al.ly,ally.sh##script:inject(popads.net.js)
@@||al.ly^$generichide
@@||ally.sh^$generichide
````
The `noeval.js` fixes another popup that occurs, atleast on my end, when you click "Skip This Ad".

**Comment by jspenguin2017** [comment]
@okiehsch Are you sure `noeval.js` won't break the the whole web page?

**Comment by okiehsch** [comment]
I don't see any breakage, do you?
As far as I can tell the site use `eval` for
1. anti-adblocking
2. triggering a popup via `replase.tk/45024.js`

I looked at `https://al.ly` and I can register or create a shortened link without problem.

**Comment by jspenguin2017** [comment]
I'll test everything out when I have time. Thanks for the input.

**Comment by uBlock-user** [comment]
So are you going to use AdsByPasser solution or stick to the filters ?

**Comment by jspenguin2017** [comment]
@uBlock-user For AdsBypasser's solution, I need to port it and test it, which is a bit complex, I'll do it later. Our solution is working OK for now. So it's not urgent, I'll do it eventually.

**Comment by uBlock-user** [comment]
Is it still being tested or are we done with this ?

**Comment by jspenguin2017** [comment]
@uBlock-user I'll do it eventually. I'm working on something else right now.

**Comment by jspenguin2017** [comment]
https://github.com/reek/anti-adblock-killer/issues/3175
Well, we got patched.

**Comment by jspenguin2017** [comment]
It somehow works again...

**Comment by jspenguin2017** [comment]
First domain fixed, opening an new issue for 2nd as they are not as related as we thought. #200
