### ISSUE TITLE
pogdesign.co.uk

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#149]
test link:

http://www.pogdesign.co.uk/cat/

![capture](https://cloud.githubusercontent.com/assets/15007183/25063686/8a4488b2-21b9-11e7-92ca-44974bad8920.PNG)

**Comment by uBlock-user** [comment]
try - `pogdesign.co.uk##.replace`

**Comment by xxcriticxx** [comment]
yes that did the trick thank you @uBlock-user

**Comment by jspenguin2017** [comment]
Added to List. Thanks.

**Comment by uBlock-user** [comment]
It was only an Adblock notice, so a cosmetic filter is sufficient.

**Comment by jspenguin2017** [comment]
Looks like this is fixed, I'll close this issue now, please let me know if something is wrong.
