### ISSUE TITLE
paczamy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#150]
test link:

http://paczamy.pl/filmy-online/27254-logan-wolverine

click on openload 

![capture1](https://cloud.githubusercontent.com/assets/15007183/25071132/b439d31a-227d-11e7-90a0-0e02a9e35f41.PNG)

you get this:

![capture](https://cloud.githubusercontent.com/assets/15007183/25071133/bc872022-227d-11e7-8419-bb40fc114a7a.PNG)

**Comment by ghajini** [comment]
fine here
![screenshot 1](https://cloud.githubusercontent.com/assets/20338483/25071238/93306254-22cf-11e7-986a-91c1ce05e1b7.png)

**Comment by xxcriticxx** [comment]
@ghajini do you have us ip?

**Comment by xxcriticxx** [comment]
@ghajini click on the second openload link

**Comment by ghajini** [comment]
Nope...i will try us ip

**Comment by xxcriticxx** [comment]
try with the second link first one is ok

**Comment by ghajini** [comment]
second link also works

**Comment by xxcriticxx** [comment]
must be only me i guess

**Comment by uBlock-user** [comment]
Nothing to do with US IP, openload is patched by the Script.

**Comment by xxcriticxx** [comment]
i removed script and list then reinstalled it i still get it but only at the second link 

![capture](https://cloud.githubusercontent.com/assets/15007183/25071809/9028f6c0-228e-11e7-8da6-885ee7e49921.PNG)

**Comment by uBlock-user** [comment]
remove all cache and site data and try again.

**Comment by xxcriticxx** [comment]
yep that did the trick

**Comment by jspenguin2017** [comment]
It works fine here...
