### ISSUE TITLE
filmik.tv

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#151]
same openload adblock 

test link:

http://filmik.tv/video/264407/maly-rycerz-trenk-hd-ritter-trenk-2015-hd/

![capture](https://cloud.githubusercontent.com/assets/15007183/25071228/a9f316da-227f-11e7-99b9-e0cb4bfd76a1.PNG)

**Comment by ghajini** [comment]
unable to reproduce

**Comment by uBlock-user** [comment]
Already patched by the Script.

**Comment by jspenguin2017** [comment]
It works fine here. 
![image](https://cloud.githubusercontent.com/assets/7283682/25072015/5981dbfc-2282-11e7-8e53-90c0ee70d952.png)
