### ISSUE TITLE
filmyiseriale.net

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#152]
test link:
http://www.filmyiseriale.net/filmonline/19938/beauty-and-the-beast-2017.html

can you add this to bypass 20sec counter:
`filmyiseriale.net#%#AG_onLoad(function() { konik = 1; });`

![3c5b9bd6-2281-11e7-8b57-3641957d5dce](https://cloud.githubusercontent.com/assets/15007183/25075352/b8390c52-22e0-11e7-8c8c-7a4b1d60bd00.PNG)

**Comment by jspenguin2017** [comment]
OK, I'll have a look.

**Comment by xxcriticxx** [comment]
@jspenguin2017 please remove contribution tag no contribution from me i found this at adguard

**Comment by uBlock-user** [comment]
`filmyiseriale.net#%#AG_onLoad(function() { konik = 1; });`

That's only supported in Adguard, not in uBO, will not work.

**Comment by uBlock-user** [comment]
If you want to kill that timer then  add - `a.timewarp("setInterval", /^1000$/);`

**Comment by jspenguin2017** [comment]
@uBlock-user We have an equivalent: 
```JavaScript
a.on("DOMContentLoaded", function() { konik = 1; });
```

**Comment by jspenguin2017** [comment]
Awesome. Fix added to Script.

**Comment by jspenguin2017** [comment]
Looks like this is fixed, I'll close this issue now, please let me know if something is wrong.

**Comment by jspenguin2017** [comment]
Domain died, dropping rule.
