### ISSUE TITLE
Stop auto play on onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#153]
test link:

http://technowinki.onet.pl/niepokorni-nieletni-w-sieci-czy-sa-bezkarni/tyftts

@jspenguin2017 can you do something to stop video auto play on this site?

**Comment by jspenguin2017** [comment]
OK, I'll have a look.

**Comment by jspenguin2017** [comment]
I think this should work. 
```JavaScript
a.observe("insert", function (node) {
    if (node && node.firstChild && node.firstChild.tagName === "VIDEO") {
        node.firstChild.onplay = function () {
            this.onplay = null;
            a.win.setTimeout((function () {
                this.pause();
            }).bind(this), 1000);
        };
    }
});
```
Had to use some duct tape, might not work as well on another device, let me properly test it out.

**Comment by jspenguin2017** [comment]
Hi, this is fixed, the video poster will not properly show, but everything else behaves as expected. 
The disable autoplay option is now off by default since some of our implementation are not really clean.

**Comment by xxcriticxx** [comment]
this is working ok to close this
