### ISSUE TITLE
sport1.de

### ISSUE THREAD

**Issue by m4rcs** [jspenguin2017/AdBlockProtector#154]
Link: http://www.sport1.de

On Safari with Tampermonkey and uBlock-safari it forwards me just to a banner

<img width="1649" alt="screen shot 2017-04-19 at 16 54 15" src="https://cloud.githubusercontent.com/assets/1042745/25186588/df58ab3e-2520-11e7-8f8c-1aaecfda5e98.png">

**Comment by jspenguin2017** [comment]
After testing, this website is working fine on all of our supported browsers. 
![image](https://cloud.githubusercontent.com/assets/7283682/25186898/c0a3f8b6-24de-11e7-9e88-5fc0596a31ba.png)
I also tested on Opera and FireFox, cannot reproduce the issue.

**Comment by uBlock-user** [comment]
Can't reproduce. Remove all cache and cookies and try again.

**Comment by okiehsch** [comment]
You should consider removing
````
@@|http://$script,domain=sport1.de
@@|https://$script,domain=sport1.de`
`````
from `AdBlockProtectorList.txt`.

**Comment by jspenguin2017** [comment]
@okiehsch Yea... Looks like those filters do nothing useful. I removed them.

**Comment by jspenguin2017** [comment]
Since there is no response, I assume that this issue is fixed and I'll close this issue now.
