### ISSUE TITLE
ovar.io

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#155]
https://www.ovar.io/

https://github.com/reek/anti-adblock-killer/issues/3105

> The notice appears when you click on Scout, Tank and Ghost

**Comment by uBlock-user** [comment]
Can you reproduce ?

**Comment by jspenguin2017** [comment]
Yes.

**Comment by uBlock-user** [comment]
Easylist is blocking all connections to - `imasdk.googleapis.com` which it checks and puts that notice.

**Comment by jspenguin2017** [comment]
Update: 
The fix: `@@||imasdk.googleapis.com^$third-party,domain=ovar.io`
Thanks to @uBlock-user

**Comment by jspenguin2017** [comment]
@uBlock-user 
>@jspenguin2017 Could you please test this filter `|blob:$domain=ovar.io` and check if it breaks anything ? Remove the exception filter I posted and add that.

**Comment by uBlock-user** [comment]
This is the script which run `addEventListener` to check whether ads are blocked or not - http://static.miniclipcdn.com/js/sdk/v1.3/miniclip.js I couldn't use anything that would stop or falsify detection, so I'm leaving it to you.

If you're going to use whitelisted filter as the solution then lets limit the third-party exposure by only whitelisting the script which is needed and not the entire domain, so the proper filter will be `@@||imasdk.googleapis.com/js/sdkloader/outstream.js$script,domain=ovar.io`

**Comment by jspenguin2017** [comment]
OK, I'll test it out. Thanks.

**Comment by jspenguin2017** [comment]
Thanks for your help, the filter is updated.
