### ISSUE TITLE
microify.com, riffhold.com (adf.ly related)

### ISSUE THREAD

**Issue by shimizurei** [jspenguin2017/AdBlockProtector#156]
Coupled with adfly redirect.

ex: microify.com/IKN

Edit: also riffhold.com/Xiq

**Comment by uBlock-user** [comment]
Yes, both of these domains need to be added to the `adf.ly` list.

**Comment by jspenguin2017** [comment]
Thanks. Added to Adfly match list.

**Comment by jspenguin2017** [comment]
Adfly updated their code... I'll close this issue, please head over to https://github.com/jspenguin2017/AdBlockProtector/issues/157 .
