### ISSUE TITLE
adf.ly

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#157]
can someone test this link http://adf.ly/1mHisY am getting adblock on it.

![capture](https://cloud.githubusercontent.com/assets/15007183/25250169/8d589b10-25e2-11e7-94ed-077370bacd8d.PNG)

**Comment by jspenguin2017** [comment]
😭 They updated their code...

**Comment by jspenguin2017** [comment]
There is an issue in AdsBypasser: https://github.com/adsbypasser/adsbypasser/issues/1434

**Comment by xxcriticxx** [comment]
ok so they have to fix before we fix?

**Comment by jspenguin2017** [comment]
Most likely... Unless we can come up with a fix before them...

**Comment by xxcriticxx** [comment]
good luck

**Comment by okiehsch** [comment]
````
||s1-adfly.com/show.php?url=$subdocument,redirect=noopframe,domain=adf.ly
||redirect2719.ws^$subdocument,redirect=noopframe,domain=adf.ly
````

**Comment by jspenguin2017** [comment]
@okiehsch Thanks for the rules, but we would prefer a bypass instead of a workaround. And we would like to be able to apply it to all websites in a controlled manner. 
If we could not find a better solution, I will add those rules and use `a.timewarp` to skip countdown... We might need to fight some popups too...

**Comment by okiehsch** [comment]
No problem,  FYI for the popups 
`adf.ly##script:inject(abort-on-property-write.js, Fingerprint2)`
works on my end.

**Comment by xxcriticxx** [comment]
i tested but i get shit load of popups

**Comment by okiehsch** [comment]
Interesting, I tried your link `http://adf.ly/1mHisY` and on my end, Chrome 58, uBO default settings I get
no popups if I add `adf.ly##script:inject(abort-on-property-write.js, Fingerprint2)`
If I do not add this filter, I get a popup, trying to redirect me through `https://leversions.info`,
if I click anywhere.

**Comment by xxcriticxx** [comment]
i tried in incognito mode let me clear history and cookies and test again

**Comment by xxcriticxx** [comment]
after i cleared history and cookies i get adblock msg again

**Comment by okiehsch** [comment]
If you
1. Open a new incognito window
2. add the filters
````
||s1-adfly.com/show.php?url=$subdocument,redirect=noopframe,domain=adf.ly
||redirect2719.ws^$subdocument,redirect=noopframe,domain=adf.ly
adf.ly##script:inject(abort-on-property-write.js, Fingerprint2)
````
3. Go to `http://adf.ly/1mHisY`
You still get the adblock message, the popups, or both?

**Comment by jspenguin2017** [comment]
Adfly is pretty polymorphic... So it is possible that the detection code is testing another domain after a few refreshes.

**Comment by lain566** [comment]
don't work in bluenik.com  
`http://bluenik.com/7VT`

**Comment by jspenguin2017** [comment]
The rule only cover `adf.ly` domain. And it's a workaround.

**Comment by jspenguin2017** [comment]
If we can find an algorithm that transforms these: 
```JavaScript
var smk = 'Z3TMNTkOMkTZJmmYYy2gNTlMNkGBQjwNNm2NJjkYN1TE';
var ref_i = 'eyJ1cmwiOm51bGwsImRvbWFpbiI6bnVsbH0=';
var ysmm = 'ZhTJNloVdTHZRGwWOniN81vIYGmtlmuWY5mJ9z4LLvml';
```
To this: 
`http://binbox.io/2yZkF#SgXfSVRa`

Then we can update our script to bypass Adfly directly like before.

**Comment by jspenguin2017** [comment]
It turns out that my quick test was flawed and all they did was changing the variable name...

**Comment by xxcriticxx** [comment]
yep doesnt matter if i flush or go private mode i still get adblock 

possible code change again? before i was getting popups

**Comment by jspenguin2017** [comment]
Wait wait, I haven't pushed out the patch...

**Comment by jspenguin2017** [comment]
OK, I rolled out the patch, I am still not confident enough to set it to be generic by default. The new version will stop the page as soon as we have enough information, which means I won't be able to display the "bypassed" message.

**Comment by jspenguin2017** [comment]
👍 Good job Adfly, now our solution is even faster.

**Comment by xxcriticxx** [comment]
whats the new ver number?

**Comment by xxcriticxx** [comment]
6.175 right?

**Comment by xxcriticxx** [comment]
code is from easylist forum maybe you want to add all domains 

```
j.gs,q.gs,adf.ly,ay.gy#@##bottom
@@||q.gs^$generichide
@@||j.gs^$generichide
@@||adf.ly^$generichide
@@||ay.gy^$generichide
@@|http://*/popunder.gif|$domain=j.gs|q.gs|adf.ly|ay.gy
@@||adf.ly/static/js/$script,domain=j.gs|q.gs|adf.ly|ay.gy
@@||ay.gy/static/js/$script,domain=j.gs|q.gs|adf.ly|ay.gy
@@||ajax.googleapis.com^$script,domain=j.gs|q.gs|adf.ly|ay.gy
@@||static.adf.ly/static/image/ad_top_bg2.png$image
@@||s1-adfly.com/show.php?url=$subdocument,third-party,domain=j.gs|q.gs|adf.ly|ay.gy
@@||redirecting.ws/?$subdocument,third-party,domain=j.gs|q.gs|adf.ly|ay.gy
@@||redirect2719.ws/?$subdocument,third-party,domain=j.gs|q.gs|adf.ly|ay.gy
```

**Comment by jspenguin2017** [comment]
All those domains are already added. I was wondering why on Earth ads are coming in, turns out EasyList was white listing them... Doesn't matter now, our script will kill the page so fast that it won't have a chance to load any ads.

**Comment by xxcriticxx** [comment]
you welcome

**Comment by uBlock-user** [comment]
Love the new solution, this is what I wanted from the beginning, it came and went in a flash!

**Comment by uBlock-user** [comment]
If they change the variable again will it stop our solution from working ?

**Comment by jspenguin2017** [comment]
Yes... I will update it by then.

**Comment by jspenguin2017** [comment]
@uBlock-user 
There are many ways to stop our solution from working, but I doubt Adfly devs will do it any time soon. 

Aggressive Adfly skipper is now on by default. If you have touched this settings, it will not change your settings, if you never touched that settings, then it will switch on. It can be switched off at any time and we will maintain both match and unmatch lists. 
I have added some checking to make sure it won't break other websites. It will not slow down web pages that are not using the wonderfully named variable `ysmm`, if the web page happens to use it, it will marginally slow it down on the first assignment to the variable.

**Comment by jspenguin2017** [comment]
Looks like everything is working fine. I'll close this issue now.

**Comment by adreporter** [comment]
@jspenguin2017 https://github.com/jspenguin2017/uBlockProtector/blob/master/Notes/Adfly%20Domains.MD
If I "mouse scroll click" twice on each domain, the second opened page will give me "Please wait 8 seconds...". Is this normal?
The exeption is http://q.gs/AtRuw which on the second attemp it will give you a "blue screen" and the URL will be `http://q.gs/ad/locked?url=AtRuw&t=s&subid=1924160`
Could you please fix it?
