### ISSUE TITLE
bc.vc

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#159]
http://bc.vc/pI9Z7Qe

https://github.com/reek/anti-adblock-killer/issues/3118

**Comment by jspenguin2017** [comment]
Block popup - thanks to @uBlock-user 
Block `bc.vc/efes.js` and all `third-party` connections.

**Comment by ghajini** [comment]
i can see unnecessary popups on clicking ''skip ad''
![screenshot 5](https://cloud.githubusercontent.com/assets/20338483/25494515/87fe51ea-2b97-11e7-8b04-e73d186857d2.png)

**Comment by jspenguin2017** [comment]
I think it is not reCaptcha protected, we might be able to hop over it like Adfly.

**Comment by uBlock-user** [comment]
The website in question is in Maintainence Mode at the moment, so cannot investigate further. Also the filter I posted along with the suggestion to block all third-party connection is actually a solution rather than a workaround for popups and all other annoyances FYI

**Comment by jspenguin2017** [comment]
@uBlock-user Thanks for the information. I marked it as workaround since we cannot cleanly skip it yet, I'll explore different solutions and use the best.

**Comment by uBlock-user** [comment]
For `bc.vc/efes.js` if you don't want to block it, then we can use `a.readOnly("cookieExpire", function (){});`

or patch BetterPopJs variable.

**Comment by jspenguin2017** [comment]
`efes.js` seems to be gone... 
![image](https://cloud.githubusercontent.com/assets/7283682/25597439/ed624428-2e8b-11e7-9437-2ade80335c2f.png)

**Comment by uBlock-user** [comment]
Now the whole domain is down lol

**Comment by jspenguin2017** [comment]
I guess it's up now...

**Comment by uBlock-user** [comment]
Yes, that file has been removed from loading, but as long as you're blocking 3rd party connections, you won't have any popups/unders.

**Comment by jspenguin2017** [comment]
The popup is now gone 😄 Some other filter took care of it. 
I added countdown skipping logic.

**Comment by jspenguin2017** [comment]
Still works. Closing.

**Comment by adreporter** [comment]
@jspenguin2017 Hi, I noticed that if you click on SKIP AD "too early" it won't redirect you to the correct page or it will close the tab. Can you have a look?

**Comment by adreporter** [comment]
I'm not using AdsBypasser anymore.
