### ISSUE TITLE
futbolchile.net

### ISSUE THREAD

**Issue by Gonzalox** [jspenguin2017/AdBlockProtector#160]
http://futbolchile.net/ (and subpages)

When finished loading the website, a few seconds pass and a message appears from blockadblock.com.

Chrome 64 + uBo (w/ Adblock Warning Removal List on) + AdBlockProtector.

Thanks!

**Comment by jspenguin2017** [comment]
Does this work? `futbolchile.net##script:inject(bab-defuser.js)`

**Comment by Gonzalox** [comment]
Yes. It works!

Thx.

**Comment by uBlock-user** [comment]
Can't reproduce. It's `eval` based so I guess the script has already patched it.

**Comment by jspenguin2017** [comment]
Added to List.
