### ISSUE TITLE
comicbook.com

### ISSUE THREAD

**Issue by Zhangsun321** [jspenguin2017/AdBlockProtector#166]
chrome
tamper
ublock

ty :)

**Comment by uBlock-user** [comment]
What is it now ? You will have describe the situation and not just copy-paste from Reek's repo.

Also it's already patched here fyi

**Comment by uBlock-user** [comment]
https://github.com/jspenguin2017/AdBlockProtector/issues/85

**Comment by Zhangsun321** [comment]
sorry.. i just switched to this from reek...    
85 fixed it... sorry...  ty...

**Comment by uBlock-user** [comment]
It's already patched in the Script. So once you install the script, it will start working, simple as that.
