### ISSUE TITLE
NSFW - gaybeeg.info

### ISSUE THREAD

**Issue by phineasmax** [jspenguin2017/AdBlockProtector#168]
Hi.
Maybe that site still tracked adblock because when I click or move the cursor to download box, it redirect me to the adblock site (http://gaybeeg.info/adblock-instructions/)
Please check again. Thanks

**Comment by uBlock-user** [comment]
Uh..no, it works fine.

**Comment by phineasmax** [comment]
@uBlock-user Can you tried it for maybe 5-7 times?
Because I tried on two PCs and two IP addresses. It didn't redirect me when I used IE without Adblock. But when I use firefox with adblock, it will redirects me to the http://gaybeeg.info/adblock-instructions/

**Comment by uBlock-user** [comment]
Hmmm okay it seems to happen alternatively, once it works, once it doesn't. It appears that they changed the variable for check and added few more ad-servers for checking. For gaybeeg.info, you can just block the inline-script so to not play this game of cat and mouse.

add - `||gaybeeg.info^$inline-script`

**Comment by phineasmax** [comment]
@uBlock-user Can't download. The download button is grey instead of green after I add that

**Comment by uBlock-user** [comment]
Not on my end - the button is green and working - 

![](https://i.gyazo.com/38c321846f619a150a916e65bc4939ae.png)

Make sure to clear all cookies and site data.

**Comment by phineasmax** [comment]
I did. But it still grey.
![1](https://cloud.githubusercontent.com/assets/21326718/25556962/a9ba023e-2d31-11e7-86c1-ca5300c2809c.png)
![untitled](https://cloud.githubusercontent.com/assets/21326718/25556964/ad517ba2-2d31-11e7-97eb-db0ff3233e5a.png)

**Comment by uBlock-user** [comment]
Disable all other extensions and then try again,

**Comment by jspenguin2017** [comment]
Hi, you do not need any custom filter, install Script and List, and it should work. Please direct further question here: https://github.com/jspenguin2017/AdBlockProtector/issues/164

**Comment by uBlock-user** [comment]
@jspenguin2017 It works but alternatively, it works once and then on refresh it leads you to the aformentioned URL, if you read my post you will know.

**Comment by uBlock-user** [comment]
Offtopic - FYI the List has now been added to uBO's stock Filterlists - https://github.com/gorhill/uBlock/commit/3ce66a4780b4615d9977f741c2f6f489ec7bb5a0

**Comment by jspenguin2017** [comment]
@uBlock-user Oh, that's great.

**Comment by uBlock-user** [comment]
He added the instructions for complete installation like he did with AAK.

**Comment by jspenguin2017** [comment]
@uBlock-user Oh, I didn't notice that... Eh, I hope other people will...
