### ISSUE TITLE
shorte.st and related domains

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#169]
Need to remove timer. 

clkmein.com/qICV9i
cllkme.com/qICV9i
viid.me/qICV9i
sh.st/qICV9i
wiid.me/qICV9i
clkme.me/qICV9i

Thanks to @lain566

**Comment by uBlock-user** [comment]
They're all the same, captcha-free so they should be able to bypass.

**Comment by jspenguin2017** [comment]
OK, looks like they added some new checks, it no longer works with uBO enabled. 
![image](https://cloud.githubusercontent.com/assets/7283682/25597558/8ca8a0ae-2e8c-11e7-9782-47842ad0d4f9.png)

**Comment by uBlock-user** [comment]
I cannot reproduce that. The timer runs, I click skip ad and it takes me to another URL shortener.

**Comment by lain566** [comment]
@uBlock-user Yes, redirect to  `linkshrink.net`
I found this, i don't know if it will work
https://github.com/denysvitali/shortest-skipper

**Comment by jspenguin2017** [comment]
@uBlock-user Hum... It's working now... Interesting... 
@lain566 Thanks, I'll investigate.

**Comment by uBlock-user** [comment]
> This library helps you skip shorte.st links programmatically (you still have to wait 5 seconds)

That doesn't make sense. How can you skip and yet have to wait for 5 seconds ? Contradicting itself in the line ?

**Comment by jspenguin2017** [comment]
@uBlock-user It is written in Crystal, I don't have any experience with that, but I assume that it's for some automation. Skip programmatically doesn't mean skip immediately.

**Comment by uBlock-user** [comment]
It's pointless if it cannot bypass, defeats the purpose of having it in the first place.

**Comment by jspenguin2017** [comment]
Pointless for us... maybe... I think the timer might be on the server side...

**Comment by szymon1118** [comment]
@jspenguin2017 @uBlock-user I found that they store destination url here: `app.options.intermediate.destinationUrl` but it can be used only when timer ends so there is a possibility to set `app.options.intermediate.timeToWait` to 0 or maybe crashing a counter would have done the same. I hope it's going to help.

**Comment by jspenguin2017** [comment]
Hum, that is not exactly how it works... We probably have to `a.timewarp` it... 
![image](https://cloud.githubusercontent.com/assets/7283682/26027204/13ad8428-37c7-11e7-9247-cd9d579f1949.png)

**Comment by jspenguin2017** [comment]
They now have reCaptcha... 
![image](https://cloud.githubusercontent.com/assets/7283682/26036108/04ae37f0-3895-11e7-83b2-ef8adc1128cb.png)

**Comment by jspenguin2017** [comment]
Looks like they have server side check, it will return 404 if we request too early...

**Comment by jspenguin2017** [comment]
Since it doesn't have any functioning ad block detection, there isn't much we can do here, so I'll close this one.

**Comment by adreporter** [comment]
@jspenguin2017 
Test link: http://sh.st/9t0Vp
The "SKIP THIS AD" button doesn't work.
Last time I visited this site was about one week ago and it worked fine.
Screenshot of the webpage:
<img width="960" alt="asas" src="https://user-images.githubusercontent.com/18214146/28132223-7d114ae0-673c-11e7-92c1-c6026fedd393.PNG">
Screenshot of the console:
<img width="563" alt="dsfsdfsd" src="https://user-images.githubusercontent.com/18214146/28132266-9acd3c24-673c-11e7-9528-897751acf055.PNG">
If I disable your extension I see this:
<img width="306" alt="dfsfs" src="https://user-images.githubusercontent.com/18214146/28132388-00625c86-673d-11e7-90e4-1997abfe5156.PNG">
Could you please fix it?

**Comment by jspenguin2017** [comment]
The link is a torrent link, do you have a torrent client installed? 
![image](https://user-images.githubusercontent.com/7283682/28133164-5607a984-66fc-11e7-9fab-6b709b0970e1.png)

**Comment by adreporter** [comment]
@jspenguin2017 No, I don't. Just found another sh.st link and it works. Sorry for spamming.

**Comment by jspenguin2017** [comment]
Yep, added.

**Comment by lain566** [comment]
@jspenguin2017 Ohh, that's great!
I forgot, you could add these domains belonging to shorte.st
```
shorte.st
sh.st
xiw34.com
clkme.me
cllkme.com
clkmein.com
corneey.com
ceesty.com
destyy.com
festyy.com
gestyy.com
viid.me
wiid.me
5k4i.com
pj45.com
jnw0.com
0px.me
blo.bs
n4gk.com
juy.be
```

**Comment by jspenguin2017** [comment]
The last few domains are causing security error in Chrome, they are not added. The rest are added.

**Comment by lain566** [comment]
@jspenguin2017 I know, I assume these domains were used for phishing or malware.

Here I have more domains to add
```
iklan.master-cyber.com
links.orgasmatrix.com
wik34.com
zryydi.com
```

**Comment by jspenguin2017** [comment]
Added.

**Comment by lain566** [comment]
@jspenguin2017 Add `skiip.me`
