### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#172]
adblock protector eats right side of the page 

with adblock protector:

![capture1](https://cloud.githubusercontent.com/assets/15007183/25564026/96e22f88-2d77-11e7-88f3-5003b0745007.PNG)

with out adblock protector:

![capture2](https://cloud.githubusercontent.com/assets/15007183/25564029/abc50bfa-2d77-11e7-8248-34b54f817354.PNG)

**Comment by jspenguin2017** [comment]
There is a bug in Core... I'll fix it.

**Comment by jspenguin2017** [comment]
This should be fixed now.

**Comment by xxcriticxx** [comment]
works thx

**Comment by jspenguin2017** [comment]
Good. Closing this issue then.
