### ISSUE TITLE
temp-mail.org

### ISSUE THREAD

**Issue by ylluminate** [jspenguin2017/AdBlockProtector#174]
http://temp-mail.org/ is not working on reading inbox messages.

**Comment by ghajini** [comment]
Welcome to this project.... Does that site display any `adblock warning ` or `prevent you` from using adblock....

**Comment by uBlock-user** [comment]
Not working how ? Provide more details.

**Comment by ylluminate** [comment]
This middle section you see here is what is presented to the user:
![example](https://cl.ly/2h3Y1b1N141l/example.jpg)

**Comment by uBlock-user** [comment]
Okay, I can reproduce.

It happens when you open an e-mail.

Add - `temp-mail.org##script:inject(abort-on-property-read.js, checkadBlock)`

**Comment by uBlock-user** [comment]
@jspenguin2017 add - `a.readOnly("checkadBlock", function ( ) { });`

**Comment by jspenguin2017** [comment]
@uBlock-user Thanks, I'll test it out.

**Comment by uBlock-user** [comment]
anti adblock script FYI

```javascript
<!-- Adblock detect -->
<script src="https://temp-mail.org/js/antiblock.js"></script>
<script src="https://temp-mail.org/js/google.js"></script>
<script>
    var adblocked = window.adblocked;

    function checkadBlock() {
        if ($('.adblockMailView').length == 0) return;

        $('#antiAdblockBtn').click(function() {

            adblocked.check(function(error, result) {
                var event = {};
                if (result) {
                    event = {
                        category: 'adblock',
                        action: 'window',
                        label: 'active'
                    };
                } else {
                    event = {
                        category: 'adblock',
                        action: 'window',
                        label: 'deactivated'
                    };
                }
                gevent(event);
            });

            var adblockClicksCount = $.cookie('adblockClicksCount');
            if (adblockClicksCount !== undefined) {
                $.cookie('adblockClicksCount', parseInt(adblockClicksCount) + 1, {
                    path: '/'
                });
            } else {
                $.cookie('adblockClicksCount', 1, {
                    path: '/'
                });
            }

            window.location.reload(true);
        });

        adblocked.check(function (error, result) {
            if (result) {
                try {
                    var event = {
                        category: 'adblock',
                        action: 'abdlock_detected',
                        label: 'abdlock_detected'
                    };
                    gevent(event);

                    var adblockClicksCount = $.cookie('adblockClicksCount');
                    if (adblockClicksCount!==undefined && parseInt(adblockClicksCount)>3){
                        $.cookie('adblockClicksCount', 1, {
                            path: '/'
                        });
                    }

                    if (adblockClicksCount==undefined || parseInt(adblockClicksCount)<=3) {
                        var antiAbblockBlock = $('.adblockMailView');
//                        antiAbblockBlock.detach();
                        $('.mailView').detach();
                        antiAbblockBlock.appendTo('.mainMailViewBl');
                        $('.adblockMailView').show();
                    }
                } catch (e) {}
            }
        });
    }
    $(window).on('statechangecomplete', checkadBlock);
    checkadBlock();
</script>
```

**Comment by jspenguin2017** [comment]
@uBlock-user Thanks for your help :smile: It's added to Script.

**Comment by ylluminate** [comment]
Thanks guys! Works great! Is there a way to make this work in Safari at present? The uBlock ext doesn't seem to allow this to run on Safari like it does on Chrome.

**Comment by jspenguin2017** [comment]
No, we don't support Safari for now.

**Comment by ylluminate** [comment]
Hah, well, I just updated the userscript via TamperMonkey and it did work for temp-mail.org, but on another test site, it works for in Chrome it doesn't work for in Safari so I guess there's some hit-and-miss scenarios here in Safari.

**Comment by jspenguin2017** [comment]
What is the other test site? Our solution is bonded to domain, so it would not work on a similar website.

**Comment by ylluminate** [comment]
@jspenguin2017 pulled this out of the air from this site: 
http://www.thewindowsclub.com/windows-modules-installer-worker-high-cpu-disk-usage

I also just tried to install uBlock Origin for Safari (removed the old uBlock fork version) from [here](https://github.com/el1t/uBlock-Safari/releases) and unfortunately it still doesn't block blockers from that domain interestingly.

**Comment by jspenguin2017** [comment]
Can't reproduce that, `thewindowsclub.com` works fine for me.

**Comment by ylluminate** [comment]
How strange... Works fine in Chrome and just won't with uBlock Origin on Safari. Will see if I can troubleshoot more at some point when I have some more time, but at least it is working on the one for which this ticket was submitted! ;)

**Comment by uBlock-user** [comment]
First, uBlock has nothing to do with this script. Secondly, uBlock for Safari is still buggy and won't work as expected. Report bugs at the Safari repo, so the dev will fix them accordingly. 

Third, this solution is ONLY for the domain in question i.e. - `temp-mail.org` There's no universal solution for anti adblock scripts. For any other domains, create a new issue.
