### ISSUE TITLE
filiser.tv

### ISSUE THREAD

**Issue by MajkiIT** [jspenguin2017/AdBlockProtector#178]
Hi, on page filiser.tv, then I have enabled yours script I can't choose player . Then I click on player nothing happen . 

test url 
http://filiser.tv/serial/okup/s01e01/the-return/17044

@xxcriticxx @F4z FYI

**Comment by jspenguin2017** [comment]
OK, I'll have a look. 

The console says `Uncaught TypeError: Cannot read property 'changeImage' of null`

**Comment by MajkiIT** [comment]
Thanks

**Comment by xxcriticxx** [comment]
```
jQuery.Deferred exception: CROPPER is null MAIN.listeners@http://filiser.tv/assets/js/scripts.1.1.4.js:39:316
MAIN.init@http://filiser.tv/assets/js/scripts.1.1.4.js:36:22
@http://filiser.tv/assets/js/scripts.1.1.4.js:139:413
j@http://filiser.tv/assets/libs/jquery-3.2.1.min.js:2:29997
g/</k<@http://filiser.tv/assets/libs/jquery-3.2.1.min.js:2:30313
 undefined  jquery-3.2.1.min.js:2:31569
TypeError: CROPPER is null[Learn More]  scripts.1.1.4.js:39:316
```

**Comment by uBlock-user** [comment]
Script is breaking the initialization of the openload player.

**Comment by jspenguin2017** [comment]
@uBlock-user Thanks, generic code is now disabled on this domain.

**Comment by jspenguin2017** [comment]
Is this good? If so, please close this issue.

**Comment by MajkiIT** [comment]
For me it's ok. 
@xxcriticxx Can you check on yours PC?

**Comment by xxcriticxx** [comment]
tested we are good

**Comment by xxcriticxx** [comment]
thx again

**Comment by MajkiIT** [comment]
@xxcriticxx thx
