### ISSUE TITLE
atresplayer.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#180]
https://github.com/reek/anti-adblock-killer/issues/3174

http://www.atresplayer.com/television/programas/dentro-de/temporada-1/capitulo-1-programa-hospital-paz_2017050101526.html

Spain Geo Lock.

**Comment by lain566** [comment]
@jspenguin2017 Solved `@@||atresplayer.com^$generichide`
https://forums.lanik.us/viewtopic.php?p=117832#p117832

**Comment by jspenguin2017** [comment]
Hum, it should make into EasyList soon. Let's wait a couple days...

**Comment by L-Sar** [comment]
@lain566 it is working for me =)

Thank you!

**Comment by lain566** [comment]
@L-Sar De nada!

**Comment by jspenguin2017** [comment]
Is this in EasyList yet?

**Comment by lain566** [comment]
Nop, add him
