### ISSUE TITLE
AdBlock Protector Script  blocks comments

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/AdBlockProtector#181]
AdBlock Protector Script  blocks comments and does not show them

http://www.lavanguardia.com/internacional/20170504/422273050377/facebook-lucie-myslikova-scout-neonazi-republica-checa.html

It should look like this
![facebook_lucie _la_scout_que_planto_cara_a_un_neo_2017-05-06_21-00-04](https://cloud.githubusercontent.com/assets/27441315/25775382/408bf740-32a4-11e7-88be-26bf4112895b.jpg)

**Comment by jspenguin2017** [comment]
That's exactly what it looks like for me. What's your setup? 
![image](https://cloud.githubusercontent.com/assets/7283682/25775796/e1107a22-326a-11e7-9e01-3754d834a76a.png)

**Comment by lain566** [comment]
I do not get it, the number of running scripts is 7

![facebook_lucie _la_scout_que_planto_cara_a_un_neo_2017-05-06_23-24-53](https://cloud.githubusercontent.com/assets/27441315/25776054/0e43c7b2-32b4-11e7-93a3-1126c9242c4c.png)

**Comment by jspenguin2017** [comment]
@lain566 It reliably load for me, are you sure Script is the source of the problem?

**Comment by lain566** [comment]
Same problem with adsbypasser.
If I disable Adblock protector scritp and adsbypasser, the comments load normally.

**Comment by lain566** [comment]
I do not know what it could be.  I close this, because it seems the problem is not adblock protector script
