### ISSUE TITLE
goodanime.co

### ISSUE THREAD

**Issue by Mind-Walker** [jspenguin2017/AdBlockProtector#184]
http://www.goodanime.co/

Any anime i open on this site has a please disable adblock warning, it started in just 1 of the options some days ago, but now it is in all of them, and that site is heavy on the adds and now i cant block them.

Example:
http://www.goodanime.co/dragon-ball-super-episode-89

im using ublock origin, firefox with greasemonkey, with this and reek lists enabled, but still cant watch and pass the disable adblock warning

Edit: installed tampermonkey for firefox to try it and still no result.

**Comment by uBlock-user** [comment]
try these filters

```
playbb.me#@#div[style^="width:"]
easyvideo.me#@#div[style^="width:"]
videowing.me#@#div[style^="width:"]
videozoo.me#@#div[style^="width:"]
```

**Comment by Mind-Walker** [comment]
added the filter to my filters in ublock origin, cleared cache and cookies from the site, and still no use

![example](https://cloud.githubusercontent.com/assets/28541715/25821774/43fc2d88-342e-11e7-97cb-42e39c80665c.jpg)

**Comment by uBlock-user** [comment]
Didn't I tell you to click on Close and Continue ?

**Comment by Mind-Walker** [comment]
Im sorry but, you kinda did not, but i still did it and it just expands the warning.

![example2](https://cloud.githubusercontent.com/assets/28541715/25821929/d200a5aa-342e-11e7-9b11-03e78be2e66b.jpg)

**Comment by jspenguin2017** [comment]
@uBlock-user That works for me, I'll use Script to remove the warning background

**Comment by Mind-Walker** [comment]
then im doing something wrong? i don't know really, i'm new on this things...

**Comment by uBlock-user** [comment]
> you kinda did not
https://github.com/jspenguin2017/AdBlockProtector/issues/184#issuecomment-299966303

You probably missed it, it doesn't matter. That message is embedded inside the iframe and can't be removed by uBO as uBO can't dig inside the iframe of the player.. Maybe @jspenguin2017 can't patch it via the script, so you will have to click on close and continue.

**Comment by jspenguin2017** [comment]
@uBlock-user Even though I can click on the button for you, I don't think that's a good idea, you'll have 4 videos playing together. I'll just remove the image.

**Comment by Mind-Walker** [comment]
I dont mind clicking at all but has i showed..for me it just expands the warning bigger and does nothing if i click on continue :\ .

**Comment by uBlock-user** [comment]
videos don't play unless and untill you click on the Close and Continue button

**Comment by jspenguin2017** [comment]
@Mind-Walker What's your setup?

**Comment by Mind-Walker** [comment]
firefox with greasemonkey, ublock origin and reek and adblock protect lists enabled, also tried to install and and adblock protect to tampermonkey and still the same :(.

**Comment by jspenguin2017** [comment]
Yea, FireFox does weird things, try Chrome.

**Comment by Mind-Walker** [comment]
k im gona try it out on chrome then... i say something in a minute, ty for trying to help guys.

**Comment by uBlock-user** [comment]
Also remove reek's script, it's obsolete and will cause other hindrances.

**Comment by jspenguin2017** [comment]
I removed the image with Script. And those rules are added to List. Thanks @uBlock-user 
![image](https://cloud.githubusercontent.com/assets/7283682/25822500/05a4269a-33f6-11e7-8b0a-5ce091420495.png)

**Comment by Mind-Walker** [comment]
weird, on chrome if i click on continue it plays the movie, but the same setup on firefox just makes the warning bigger and does nothing :\.

**Comment by jspenguin2017** [comment]
@Mind-Walker It's either a bug in uBO or a bug in FireFox.

**Comment by uBlock-user** [comment]
@Mind-Walker Just use 9anime.to or kissanime.ru and avoid this website.

**Comment by Mind-Walker** [comment]
ok..maybe its something with firefox, i opened firefox on secure mode with every extra off and everything off, and still warnings me about add blocking and does the same on firefox....damn wierd :\.

And ty for the new anime sites :D .

**Comment by uBlock-user** [comment]
The WebExtensions are still buggy as hell in FF and that's why uBO is not working as it's supposed to work on Chromium.

**Comment by Mind-Walker** [comment]
I reported to the site owner anyway also, that with firefox on secure mode it still warns me about adblock..and that should be impossible since in secure mode it disables all the extras and everything on firefox...and still warns me about adblocking.

**Comment by jspenguin2017** [comment]
@Mind-Walker Then it's an issue of the website.

**Comment by Mind-Walker** [comment]
Ye i noticed on chrome with everything off also, and seeing all the extreme adds, i click on continue it starts the movie but i cant maximize and see in fullscreen...so it is almost the sites fault and they are exaggerating on the adblocking issue and messed something up now.

Im going to try the new sites ublock user recommended and see if i like them and just change site all together, ty very much for the help guys.

**Comment by uBlock-user** [comment]
That adblock message is static and there is no detection going on, so just ignore it.

**Comment by jspenguin2017** [comment]
I can't ignore it, it's taunting me.

**Comment by uBlock-user** [comment]
Ofcourse, that's why you removed it.
