### ISSUE TITLE
ft.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#185]
https://github.com/reek/anti-adblock-killer/issues/3172

Test link: http://ft.com/

Ad block warning only affect people who registered an account but have not paid. 

As a side note, this website also has a pay wall which can be bypassed by entering the website from Google or by using Google WebCache.

**Comment by jspenguin2017** [comment]
I cannot reproduce the described issue since I do not have an account, and I will not register an account to test this. If someone can test this our and find a solution, please let me know.

**Comment by uBlock-user** [comment]
I have another domain where this sort of an issue is lingering for some time - https://www.wsj.com/articles/taliban-broaden-their-reach-in-villages-across-afghanistan-1494235804

It hides the news partially so I'm not sure if it's the anti adblock script in action or a nagging paywall.

**Comment by jspenguin2017** [comment]
Wall Street Journal has a pay wall, the hiding is done on the server side, the link you posted before has a section on this website: https://www.ghacks.net/2016/02/26/read-articles-behind-paywalls-by-masquerading-as-googlebot/

**Comment by uBlock-user** [comment]
Sounds like a pain in the ass type of job! I'm not that desperate to read news which I can do on Google.

**Comment by uBlock-user** [comment]
Workaround for WSJ, archive the entire article at http://archive.is/ and then read it.

Example - earlier archive article - http://archive.is/ClxNg

**Comment by jspenguin2017** [comment]
@uBlock-user Well, that is just as painful. Maybe we can make another Userscript that does that for us.

**Comment by uBlock-user** [comment]
Yes, an optional script will do it. Only for those who're interested in reading pay-walled articles.

**Comment by jspenguin2017** [comment]
OK, I'll consider this when I have time.

**Comment by jspenguin2017** [comment]
This is out of the scope of this project and I don't support bypassing paywall that much. If someone wants to start a project that bypasses paywalls, please do so.
