### ISSUE TITLE
tf1.fr

### ISSUE THREAD

**Issue by SohKa** [jspenguin2017/AdBlockProtector#187]
Hey !

Since recently, tf1.fr blocks his videos for adblocker users and asks them to disable it.

For example : https://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos/yann-l-henoret-l-homme-a-suivi-president-elu-pendant-8-mois.html

Can you fix it, please ?

**Comment by jspenguin2017** [comment]
Hum, I can't reproduce that, what's your setup? 
![image](https://cloud.githubusercontent.com/assets/7283682/25857597/cec2b744-3496-11e7-9046-e5fbcdde3f88.png)

**Comment by SohKa** [comment]
That's weird, it's working with Chromium+ublock (without AAK and APL script and list).

My setup is Firefox+UBO+Tampermonkey

**Comment by jspenguin2017** [comment]
FireFox is no longer supported due to excessive issues with its behavior.

**Comment by uBlock-user** [comment]
WebExtensions adoption is causing the issues in Firefox, so avoid using the browser until the stable version for each extension is released.

**Comment by HotMumu** [comment]
Hello,

I came here exactly for the same issue. I'm using Chrome with uBlock Origin + uBlock Origin Extra + TamperMonkey with "Anti-Adblock Killer 10.0 (by Reek)" and "AakList (Anti-Adblock Killer)" with both scripts installed.

Do I miss something ? Am I doing something wrong ?

Regards.

**Comment by jspenguin2017** [comment]
@HotMumu Can you configure your setup exactly like this one and try again? 
https://github.com/jspenguin2017/AdBlockProtector/blob/master/Notes/Standard%20Setup.MD

**Comment by uBlock-user** [comment]
Remove Reek's script, it will only cause issues rather than fix anything.

**Comment by HotMumu** [comment]
Done, I went for the standard setup. The first visit everything went fine then I refreshed the page and got a 20sec ad, After another refresh I got the message roughly translated "Your video will begin in 60 sec" yet the video started after the first ad (20s).

I just tried once again and this time I got two ads. It's like this thing is adapting.

Thanks for your time and help, much appreciated.

**Comment by jspenguin2017** [comment]
@HotMumu Can't reproduce, I refreshed it 3 times and the video starts playing directly all 3 times.

**Comment by HotMumu** [comment]
Ok thanks again for trying. Any other advice regarding my setup ?

I'll avoid Reek's script for now like uBlock-user suggested.

**Comment by jspenguin2017** [comment]
@HotMumu If you have the exact save setup as the standard setup, and things behave differently, then it could be caused by geolocation. Some website sends different page to different countries. Do you know to which country does your IP belongs to?

**Comment by HotMumu** [comment]
I'm from Belgium. The first try with the Apple NoteBook was in France. Both countries gave similar results.

**Comment by jspenguin2017** [comment]
@HotMumu It works consistently for me. Sorry I don't know what's wrong. 
![image](https://cloud.githubusercontent.com/assets/7283682/25969511/60940fb2-3652-11e7-8817-b286c2d90e08.png)

**Comment by lain566** [comment]
@jspenguin2017
 **EasyList Liste FR** is the source of the issue, which blocks access to this domain _churccivic.com_

![ublock _ _panel_de_control_-_google_chrome_2017-05-18_22-04-52](https://cloud.githubusercontent.com/assets/27441315/26221301/4b71cf74-3c16-11e7-95da-c7fcd0f528a8.jpg)

**Comment by Antarion** [comment]
I confirm this. With the easylist fr the video won't start.
If you disable it the ad will play.

**Comment by maxxyme** [comment]
Oh man... seriously? This is what was said in an earlier comment: the "thing" is adapting. I remember they had the same problem with canalplus.fr (which hosted the former Quotidien show - known as Le Petit Journal) and whenever they blocked in the EL FR some weird domains like this one, the player had a new one)...

**Comment by HotMumu** [comment]
Thanks you guys !

**Comment by Antarion** [comment]
So what do we do from there?

**Comment by lain566** [comment]
@jspenguin2017 Can you help?

**Comment by jspenguin2017** [comment]
@lain566 Sorry, FR list is not part of our supported setup. If I have time after my other projects, I might have a look.

**Comment by lain566** [comment]
@jspenguin2017 It's ok, I understand

**Comment by DavidLibeau** [comment]
I made a quick Chrome extension for TF1 anti-adblock : https://github.com/DavidLibeau/Tf1-adblock-fix (if it's help)

**Comment by jspenguin2017** [comment]
I already have 2 nooping rules that fixes this.
