### ISSUE TITLE
techzac.com

### ISSUE THREAD

**Issue by MonfGeiger** [jspenguin2017/AdBlockProtector#190]
using standard setup, tried opening https://www.techzac.com/enable-group-policy-editor-windows-10-home, no dice

**Comment by uBlock-user** [comment]
add - `techzac.com##script:inject(noeval.js)`

**Comment by MonfGeiger** [comment]
fixed it, but the pictures in the article (not the ones around it), don't load; can deal with it, but be nice if those could load

**Comment by jspenguin2017** [comment]
Hi, can you explain what's wrong with this website? 
![image](https://cloud.githubusercontent.com/assets/7283682/25923109/3d8a7592-3599-11e7-8f5b-3e391f44ef57.png)

**Comment by uBlock-user** [comment]
@MonfGeiger which pictures ? Provide a screenshot.

**Comment by MonfGeiger** [comment]
I am so sorry it took me this long, had some problems with my browser and irl stuff; the issue is apparently now fixed, but when it was broke, the before showed the pics that would've loaded without the protector script/ublock on, and the after shows the pics marked by red x's as not loading

![after](https://cloud.githubusercontent.com/assets/28603306/26015968/55c7429c-3720-11e7-8fe9-a0093280cefb.JPG)
![before](https://cloud.githubusercontent.com/assets/28603306/26015967/55c556da-3720-11e7-9346-d044f458f310.JPG)

as the issue is resolved, imma close this until I encounter the same or different
