### ISSUE TITLE
canalplus.fr

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#191]
From home page chat board: 

http://www.canalplus.fr/infos-documentaires/pid8488-c-21-centimetres.html?vid=1447514

![image](https://cloud.githubusercontent.com/assets/7283682/25925215/775cbf22-35a4-11e7-9367-ccc10315dfd2.png)

**Comment by uBlock-user** [comment]
Anti adblock script - http://secure-player.canal-plus.com/one/prod/v2/1.1.chunk-b1e2753a85b5c93e02e9.js

Embedded inside the player itself

**Comment by jspenguin2017** [comment]
Oh no, that is usually hard to deal with... We might need to patch the player...

**Comment by uBlock-user** [comment]
Yeah haven't exactly found what to cut off without breaking the player.

**Comment by jspenguin2017** [comment]
@uBlock-user If we can find the URL of the real media file, we can replace the entire player.

**Comment by jspenguin2017** [comment]
@uBlock-user I think a comment in #192 is meant to be here: 

>http://service.canal-plus.com/video/rest/getVideosLiees/cplus/1447514?format=json
http://secure-player.canal-plus.com/one/prod/v2/configs/cplus/prod.json
Can you find the URL from there ?

The URL seems to be in the first link... How did you find the link?

**Comment by uBlock-user** [comment]
uBO Logger, so do we have the media file link ?

**Comment by jspenguin2017** [comment]
@uBlock-user The logger is not good enough for now, until Tampermonkey has `GM_webRequest` implemented, we need to find the URL without the logger.

**Comment by uBlock-user** [comment]
I don't understand ? I found the link which I posted in https://github.com/jspenguin2017/AdBlockProtector/issues/191#issuecomment-300867672  in which video urls are instructed from which you can extract the URL

**Comment by jspenguin2017** [comment]
@uBlock-user I think it would be really annoying to have to find the URL from logger manually every time. And many people won't be comfortable doing that. Userscript does not have access to the logger.

**Comment by uBlock-user** [comment]
Yeah we can talk about that later. Lets stick to this case only. This is the URL - http:\/\/vod-flash.canalplus.fr\/WWWPLUS\/STREAMING\/1705\/05\/nip_NIP_125709_1500k.mp4

Correct ?

**Comment by jspenguin2017** [comment]
Yea, it should be `http://vod-flash.canalplus.fr/WWWPLUS/STREAMING/1705/05/nip_NIP_125709_1500k.mp4`
We need to fix the request header. Hum...

**Comment by uBlock-user** [comment]
Can you do that ?

**Comment by jspenguin2017** [comment]
@uBlock-user One day.

**Comment by uBlock-user** [comment]
will take one day  ?

**Comment by jspenguin2017** [comment]
I don't know, we'll see. One day we'll find a solution.

**Comment by szymon1118** [comment]
@jspenguin2017 @uBlock-user I found a solution by chance :smile:. We simply need no add: `?secret=pqzerjlsmdkjfoiuerhsdlfknaes` after an URL but I don't know where did it come from. I found it here: http://mg.eagleget.com/assetic/html/7594709.html

**Comment by jspenguin2017** [comment]
@szymon1118 Wow! You are so good at dealing with video sites XD
Is the secret same for every video?

**Comment by szymon1118** [comment]
@jspenguin2017 Yes, it seems that it should work for every video. We can also play m3u8 but we need to fix a videojs to handle HLS.

**Comment by uBlock-user** [comment]
@szymon1118 Good find. @jspenguin2017 That will do it ?

**Comment by jspenguin2017** [comment]
@szymon1118 Is this the right HLS plug-in? 
`<script src="//cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.4.0/videojs-contrib-hls.min.js"></script>`

**Comment by szymon1118** [comment]
@jspenguin2017 I think so. I didn't noticed any other needed libs/add-ons. There is also a newer version of the plug-in: https://cdnjs.com/libraries/videojs-contrib-hls

**Comment by jspenguin2017** [comment]
@szymon1118 Last time I tried that, it didn't work... I'll see if the new version helps...

**Comment by Slowerzs** [comment]
You can easily find the URL of any http://www.canalplus.fr : 
1) A video will be for example http://www.canalplus.fr/humour/pid1784-les-guignols.html?vid=ID
2)If you go to http://service.canal-plus.com/video/rest/getVideos/cplus/ID you will find the actual URL of the video for several qualities
3)By addiding "?secret=pqzerjlsmdkjfoiuerhsdlfknaes" you get the video 
ex : http://vod-flash.canalplus.fr/WWWPLUS/STREAMING/1705/11/nip_NIP_126304_1500k.5.mp4?secret=pqzerjlsmdkjfoiuerhsdlfknaes

**Comment by jspenguin2017** [comment]
@Slowerzs 👍 👍 👍 Thanks!

**Comment by jspenguin2017** [comment]
@Slowerzs @szymon1118 Thanks a lot, it's now patched 😄 
```JavaScript
if (a.domCmp(["canalplus.fr"])) {
    let videoID;
    const search = a.win.location.search;
    if (search.startsWith("?vid=") && (videoID = search.split("=")[1])) {
        a.ready(() => {
            GM_xmlhttpRequest({
                method: "GET",
                url: "http://service.canal-plus.com/video/rest/getVideos/cplus/" +
                videoID + "?format=json",
                onload: function (res) {
                    try {
                        const response = JSON.parse(res.responseText);
                        const url = response.MEDIA.VIDEOS.HD;
                        if (url) {
                            a.$("#onePlayerHolder").after(a.nativePlayer(url +
                                "?secret=pqzerjlsmdkjfoiuerhsdlfknaes")).remove();
                        } else {
                            throw "Media URL Not Found";
                        }
                    } catch (err) {
                        a.config.debugMode && a.out.error("AdBlock Protector failed to find media URL! ");
                    }
                },
                onerror: function () {
                    a.config.debugMode && a.out.error("AdBlock Protector failed to load media JSON! ");
                }
            });
        });
    }
}
```

**Comment by Slowerzs** [comment]
![capture](https://cloud.githubusercontent.com/assets/28687818/26037586/8ffc3738-38f6-11e7-8fb0-4304e5f213b9.PNG)
Hmm.. Still doesn't work for me
:(

**Comment by szymon1118** [comment]
@Slowerzs Try to manually update userscript in TM settings.

**Comment by jspenguin2017** [comment]
Do you have the latest Script installed? 
![image](https://cloud.githubusercontent.com/assets/7283682/26037596/d7d10d92-38b3-11e7-9d99-17f949581f36.png)

**Comment by Slowerzs** [comment]
Woops my bad, sorry

**Comment by jspenguin2017** [comment]
Looks good. Closing.

**Comment by jspenguin2017** [comment]
Wait, that's not good, the episodes below doesn't work.

**Comment by jspenguin2017** [comment]
And we should use this data, instead of the search var, since the page is fully functional (without uBO) when there is no search var. 
![image](https://cloud.githubusercontent.com/assets/7283682/26039504/d59db7a8-38d8-11e7-80ef-c55cdf6b0cd9.png)

**Comment by jspenguin2017** [comment]
I think this is good. Can someone test? It is added to Script 7.12
```JavaScript
if (a.domCmp(["canalplus.fr"])) {
    let original; //Will be set later
    let currentVideoId = null; //So we don't switch unles it's different
    let videoElem; //Current video player element, used to replace it when changing episode
    //New handler
    const newFunc = function (onglet, liste, page, pid, ztid, videoId, progid) {
        //Switch video
        if (videoId !== currentVideoId) {
            currentVideoId = videoId;
            videoSwitch(videoId);
        }
        //Run original function
        original.apply(a.win, arguments);
    };
    //Video switcher
    const videoSwitch = function (videoID) {
        debugger;
        videoElem.text("Loading...");
        GM_xmlhttpRequest({
            method: "GET",
            url: "http://service.canal-plus.com/video/rest/getVideos/cplus/" +
            videoID + "?format=json",
            onload: function (res) {
                //Try to find media URL
                try {
                    const response = JSON.parse(res.responseText);
                    const url = response.MEDIA.VIDEOS.HD;
                    if (url) {
                        const tempElem = a.$(a.nativePlayer(url + "?secret=pqzerjlsmdkjfoiuerhsdlfknaes"));
                        videoElem.after(tempElem).remove();
                        videoElem = tempElem;
                    } else {
                        throw "Media URL Not Found";
                    }
                } catch (err) {
                    a.config.debugMode && a.out.error("AdBlock Protector failed to find media URL! ");
                }
            },
            onerror: function () {
                a.config.debugMode && a.out.error("AdBlock Protector failed to load media JSON! ");
            }
        });
    };
    //Initialization
    a.ready(() => {
        //Insert our handler in between theirs
        original = a.win.changeOngletColonneCentrale;
        a.win.changeOngletColonneCentrale = newFunc;
        //Get the original player
        videoElem = a.$("#onePlayerHolder");
        //Set current video ID then patch the player for the first time
        if (currentVideoId = videoElem.data("video")) {
            videoSwitch(currentVideoId);
        }
    });
}
```

**Comment by jspenguin2017** [comment]
Still works. Closing. Let me know if something is not right.
