### ISSUE TITLE
softgames.de

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/AdBlockProtector#192]
Adblocker detected

Examples:
https://games.softgames.de/griddlers-deluxe/
https://games.softgames.de/championship-2016/
https://games.softgames.de/up-hill-racing-2/
https://games.softgames.de/toss-a-paper/

**Comment by uBlock-user** [comment]
Anti adblock script - https://games.softgames.de/assets/sg-loader.js?_v=v1.2.9

**Comment by jspenguin2017** [comment]
I'll have a look.

**Comment by uBlock-user** [comment]
Until you can patch it, this filter will work - `@@/showads.js$domain=softgames.de`

**Comment by jspenguin2017** [comment]
@uBlock-user Oh, looks like it is loaded from another script instead of a script tag. Does nooping it work?

**Comment by uBlock-user** [comment]
nooping what ?

**Comment by uBlock-user** [comment]
http://service.canal-plus.com/video/rest/getVideosLiees/cplus/1447514?format=json

http://secure-player.canal-plus.com/one/prod/v2/configs/cplus/prod.json

Can you find the URL from there ?

**Comment by jspenguin2017** [comment]
@uBlock-user The URL seems to be in the first link, is there a programmatic way to find the URL of that JSON?

**Comment by uBlock-user** [comment]
@jspenguin2017 Yeah that's a screw up on my part.

**Comment by uBlock-user** [comment]
Also it's a first party script, nooping or white-listing won't make much of a difference.

**Comment by jspenguin2017** [comment]
The rule fixed half of it, the loading waits for the ads... 
![image](https://cloud.githubusercontent.com/assets/7283682/26027328/78e539ce-37c9-11e7-837b-c6eac4d7f0b0.png)

**Comment by ghajini** [comment]
@@||games.softgames.de/assets/advertisement.js
does this work ? along with above proposed filter

**Comment by lain566** [comment]
@jspenguin2017 This might be the second anti-adblock 
https://mediamanager.softgames.de/sg-mc.js?_v=1.9.3


-
Whitelisting:
```
https://www.googletagservices.com/tag/js/gpt.js
https://securepubads.g.doubleclick.net/gpt/pubads_impl_117.js
https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&correlator=
```

**Comment by jspenguin2017** [comment]
Eh... That's like 10 000 lines of code...

**Comment by lain566** [comment]
@jspenguin2017 add 

```
||softgames.de/sg-mc.js*$script,redirect=noopjs
softgames.de##.button-image
softgames.de##.arrow-container
softgames.de##.ui-draggable-handle.ui-draggable.more-games-cross-promo-button
```

**Comment by jspenguin2017** [comment]
@lain566 Thanks. I added the first rule, others hide elements which are not really ads and not everyone wants them hidden. 
👍

**Comment by jspenguin2017** [comment]
Tested again, still works. Closing. Let me know if it breaks again.
