### ISSUE TITLE
mangas.zlx.com.br

### ISSUE THREAD

**Issue by gagabs** [jspenguin2017/AdBlockProtector#193]
Show a nag message every 10 pages. Bypass Reek and ABProtector (uBlock).

Example URL: https://mangas.zlx.com.br/manga/one-piece/130098/capitulo-865

**Comment by uBlock-user** [comment]
The page redirects to http://www.aliancaproject.com.br/

**Comment by gagabs** [comment]
Strange, it doesn't redirect for me. BTW, open https://mangas.zlx.com.br/ and try any manga, I just clicked in the first one.

**Comment by uBlock-user** [comment]
same, redirection again.

**Comment by jspenguin2017** [comment]
It redirects me to http://www.aliancaproject.com.br/ which contains a few dysfunctional links.

**Comment by xxcriticxx** [comment]
it redirects

**Comment by uBlock-user** [comment]
Can't reproduce either way.

**Comment by gagabs** [comment]
That is strange. I can reproduce that redirect in Tor browser, but not in my normal browser. I've tried an US proxy and spoofed my language headers, but still cant get the redirect. Do you have any suggestions?

**Comment by jspenguin2017** [comment]
Hum... Does it redirect in incognito mode?

**Comment by gagabs** [comment]
No. Tested in a Linux virtual machine and its doesn't redirect too.

**Comment by jspenguin2017** [comment]
It still redirect for me. Sorry, we can't help you in this case.
