### ISSUE TITLE
en.ff14angler.com

### ISSUE THREAD

**Issue by Mycah** [jspenguin2017/AdBlockProtector#195]
Forces you to use mobile site, which isn't usable.

Super annoyed, plays 2 videos ads with audio.

Example: http://en.ff14angler.com/?spot=0&fish=334&bait=0

**Comment by jspenguin2017** [comment]
`ff14angler.com#@#.adsbygoogle`
The main content has class `adsbygoogle` 😂

**Comment by Mycah** [comment]
Thanks, works.

**Comment by uBlock-user** [comment]
Proper filter - `@@||ff14angler.com^$elemhide`

**Comment by jspenguin2017** [comment]
@uBlock-user Why is that? We still want to hide other elements, just not the main panel.

**Comment by uBlock-user** [comment]
@jspenguin2017 Just by disabling one element, it can change the check and switch to another element and  the game of cat and mouse will go on. This will disable any generic elements so we're patching it for good, whatever ad elements appear after that will have to be patched individually which can be done via particular cosmetic filters.

Secondly, disabling insertion of generic elements makes uBO load the page faster and efficiently as said by the gorhill himself. So whenever you're disabling some generic hiding for an element for anti adblock, always do for all, and not just a single class.

**Comment by jspenguin2017** [comment]
@uBlock-user Ah, that makes sense. I'll update the filter.
