### ISSUE TITLE
[Announcement] Script v7

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#196]
Hi guys, it's time to do some long due maintenance to the core of the Script. 

The goals are: 

1. Make these functions to have more matching mode: string, exact string, RegExp, onbefore callback, onafter callback
    * `a.filter`
    * `a.timewarp`
2. Make these functions to be able to handle properties arbitrarily deep: 
    * `a.filter`
    * `a.readOnly`
    * `a.noAccess`
3. Make mutation observer to be able to handle removal. 
4. Grant cross origin XHR on install time. 

This means the Script would not be updated for a few days until I implement and test all these. I will start working on them tomorrow or Saturday, please let me know if the latest version, 6.209, has any bugs (this does not include the lack of solutions for specific websites), so they can be fixed before I start working on v7. 

I will be looking over every issue that stacked up during my final exams after this, but I'm not a magician so I can't guarantee when they will be fixed.

**Comment by xxcriticxx** [comment]
@jspenguin2017 are you going wrap your code in to add-on extension?

**Comment by jspenguin2017** [comment]
@xxcriticxx You can read my mind. I am seriously considering it. 
Pro: 
* People will stop asking about Greasemonkey
* Race condition will probably be better
Con: 
* Even though Script will run on every browser that supports WebExtension, which is pretty much every browser that is not obsolete, not all browsers let you easily side load extensions, and I don't want to deal with publishing it in app stores

**Comment by xxcriticxx** [comment]
no webstore needed only here news will spread

**Comment by uBlock-user** [comment]
@jspenguin2017 Please don't convert the Script to an extension for Chrome, that hinders the ability to edit or test any raw code.

**Comment by jspenguin2017** [comment]
@uBlock-user Well, we need to deal with the race condition one day... And v7 is the right time to do that. I will make an interface that allows you to edit the script temporarily if I decide to make it into an extension.

**Comment by uBlock-user** [comment]
I thought we already dealt with the race condition. Also race conditions do develop in extensions too, like with `animmex` case. Just by converting into an extension, the race condition isn't eliminated automatically.

**Comment by uBlock-user** [comment]
Keep in mind that after you create an extension, you will have to upload it to the webstore as folks won't be downloading he extension physically with every update which is a pain in the ass if you ask me.

**Comment by jspenguin2017** [comment]
@uBlock-user Well, my plan is to have a minimalist script host loading this one specific Userscript. I think it will inject faster since there isn't as much that the script host needs to worry about, and we can have more aggressive API including those that will be too unsafe for regular script host. We can also do custom redirect which frees us from uBO's resource list restriction.

**Comment by jspenguin2017** [comment]
The host itself will be updated once a blue moon, which should not be too annoying. I guess I can put it into the store as well, it's like a trimmed down version of a script host.

**Comment by uBlock-user** [comment]
That could work as you're creating a script host specifically with the embedded script inside and you will also be making the script editable as you mentioned before, but creating a script host just for this one script, won't that be lots of work for you ?

**Comment by uBlock-user** [comment]
Also would you offer to support for installing other scripts ? I'm currently using uBO-Extra as the Script, so I will also need to load that in the script host.

**Comment by jspenguin2017** [comment]
@uBlock-user Well, we can copy pages of code form Violentmonkey, what we really need is aggressive API that let me take control over the extension background page. For this reason, I can really only load trusted script, maybe I'll sign the Script for security.

**Comment by uBlock-user** [comment]
I just hate having more extensions in Chrome as they tend to slow down the browser, but with VM I could load one extension as a script so one less extension to deal with. So you're not going to offer support for other scripts ?

**Comment by xxcriticxx** [comment]
Btw Chrome was coming out with websocket support in the next version

**Comment by uBlock-user** [comment]
What do you mean ? It already did.

**Comment by xxcriticxx** [comment]
i am in ver 54 i guess its time to update

**Comment by jspenguin2017** [comment]
VM does not let me run privileged code, nor should it. I want to have access to WebRequest, and I want to be able to do custom redirect.

**Comment by uBlock-user** [comment]
So I guess you have made up your mind ?

**Comment by jspenguin2017** [comment]
@uBlock-user No, that's the plan, only the plan.

**Comment by jspenguin2017** [comment]
Here is my new plan: Get v7 out, then work on the extension later since that might take time (I never made extensions before) and I don't want to delay too many issues. 

OK, it's time to draft new APIs: 

`a.filter`: 
Current:`a.filter(function_name, regexp_matcher)`
Plan: `a.filter(function_name, enum_match_method, matcher, callback_after)`

`a.timewarp`: 
Current:`a.filter(function_name, regexp_matcher, multiplier)`
Plan: `a.filter(function_name, enum_match_method, matcher, callback_after, multiplier)`

**Comment by uBlock-user** [comment]
So v7 intially would be the script and later on wrapped into an extension ?

**Comment by jspenguin2017** [comment]
@uBlock-user Yep.

**Comment by jspenguin2017** [comment]
Plan update: enumeration index start at 1 so it is easier to compare
They accepts onMatch along with onAfter.

**Comment by jspenguin2017** [comment]
v7 is ready! I did some intense testing this afternoon and it should be good. Please let me know if it breaks. 

Highlights of new features: 

* We can now bypass our own filter by passing `a.filter.key` as last argument to a filtered function, this key is obviously private and not accessible by the webpage
* `a.filter` and `a.timewarp` now accept 4 different matching methods, they also accept "on match" and "on after" callback
* `a.filter`, `a.readOnly`, and `a.noAccess` can now handle deep properties

**Comment by jspenguin2017** [comment]
Fixed a bug in timewarp, and filter key removed, I couldn't find a nice way to pass it...
