### ISSUE TITLE
tampermonkey cannot be trusted,

### ISSUE THREAD

**Issue by FrostKnight** [jspenguin2017/AdBlockProtector#197]
it is not open source it is propreitary software, so I ask you, please support greasemonkey, or at least something a script manager that is free software.

It really isn't a good idea to make your script only workable through proprietary software. 

Also, nonfree software is defective by design.

**Comment by uBlock-user** [comment]
ViolentMonkey works fine even if's not officially supported by @jspenguin2017  You can use that as I'm using VM also.

**Comment by kowith337** [comment]
Me also, because of this,

![screenshot 124](https://cloud.githubusercontent.com/assets/16535467/26000485/5b357d4c-3753-11e7-9708-8e058141e0b3.png)

I'm abandoned to use that because it put nagging donation popup that take me extra time when I just go to dashboard and edit or manage.
Plus, the first configuration is set to send anonymous usage data back to Tampermonkey by default, I don't want that.

**Comment by Dibbyo456** [comment]
I deleted Reek's scripts, like you told me few weeks ago, should I install this one? @uBlock-user

**Comment by uBlock-user** [comment]
@Dibbyo456 Yes.

**Comment by jspenguin2017** [comment]
Greasemonkey is not available on Chrome, and it uses different security policy which means I will have to rewrite 5000 lines of code to make it compatible.

**Comment by jspenguin2017** [comment]
@kowith337 Just click "I don't want to donate", and it won't pop up again. Also, if you are so worried about statistics, why are you using Windows? It sends usage report and you don't even have an option to disable it (unless you are using Enterprise edition).

**Comment by FrostKnight** [comment]
I don't even know if there is a point supporting chrome, it is such a
bad web browser, spying and what not really makes it insecure by
design.  does greasemonkey exist on anything other than firefox? just
curious.

**Comment by jspenguin2017** [comment]
@FrostKnight If you wish to fork a version for FireFox, feel free to do so.

**Comment by uBlock-user** [comment]
> I don't even know if there is a point supporting chrome, it is such a
bad web browser, spying and what not really makes it insecure by
design.

Use Chromium, chrome is the clone.

**Comment by jspenguin2017** [comment]
@uBlock-user Do you have the documentation for Violentmonkey?

**Comment by uBlock-user** [comment]
No, will this help - https://github.com/violentmonkey/violentmonkey ?

**Comment by jspenguin2017** [comment]
@uBlock-user No, that doesn't really help.

**Comment by uBlock-user** [comment]
You can ask @gera2ld if you want have any questions.

**Comment by jspenguin2017** [comment]
@uBlock-user I don't want to spend the time to test everything out, and I can't tell him to test it out for me, that's why I need a detailed documentation.

**Comment by FrostKnight** [comment]
Well probably not, I will just wait for ff57 where it will be supported
for sure. ;)

**Comment by jspenguin2017** [comment]
@FrostKnight Where what will be supported? Firefox 57 or not, I'm not going to test on it.

**Comment by FrostKnight** [comment]
Oh I know, violentmonkey, is coming to firefox then. so it won't be an
issue I am sure.

**Comment by jspenguin2017** [comment]
@FrostKnight That remains to be seen. The buggyness of FireFox WebExtension is currently off the chart. 
And I might decide to make Script into an extension, and you will have to side load it into FireFox.

**Comment by FrostKnight** [comment]
I guess we'll just have to see what happens. Or I will anyways...

**Comment by uBlock-user** [comment]
@jspenguin2017 
Unfortunately, there's no detailed documentation as gerald never created it. Secondly, VM is based on GM and TM, so everything is same, nothing's changed.

**Comment by jspenguin2017** [comment]
@uBlock-user If that is the case, people wishing to use open source script host can already do that. So this isn't an issue then?

**Comment by uBlock-user** [comment]
@jspenguin2017 Yes it is not. It's more of a request.

**Comment by jspenguin2017** [comment]
Request of what?

**Comment by uBlock-user** [comment]
@jspenguin2017 To put in a clear word, @FrostKnight doesn't trust TM and wants you to add support for VM. I don't and majority of the others don't either as solutions are present to deal with the issues he's mentioning. He dislikes Chrome too even though he could use Chromium, so it's his plea, not anyone else's.

**Comment by jspenguin2017** [comment]
I can only test on one single setup, which would be the one I use. If someone wants to offer support for another browser or script host, please fork or clone and let me know.

**Comment by FrostKnight** [comment]
I don't have the technical skills to clone yet... so its for the best if
you close.

**Comment by jspenguin2017** [comment]
@FrostKnight I'm closing this not because I will keep things as is, but because I have decided what to do. And this does not include offering support for Greasemonkey or FireFox. My plan is making a custom script host which not only fixes our dependence on Tampermonkey but also gives us the power to do use more powerful APIs.

**Comment by FrostKnight** [comment]
Ah, okay.
