### ISSUE TITLE
9cartoon.me

### ISSUE THREAD

**Issue by uBlock-user** [jspenguin2017/AdBlockProtector#199]
Test link - http://player.9cartoon.me/?id=160211&ep_id=160211&anime=the-powerpuff-girls-2016-season-2-2017&episode=episode-7

Anti adblock script

```javascript
<script src="http://player.9cartoon.me/static/ads.js?v=1.5" type="text/javascript"></script>
<script type="text/javascript">
	if(document.getElementById('dKXaJTLMrRmZ')){
	} else {
	  setTimeout(function(){ 
		$('#player').html('<div style="text-align: center;padding-top: 200px;font-size: 20px;line-height: 28px;">Nuestro sitio es mantenido por los anuncios en el sitio, por favor, ayúdenos a mantener este sitio por desactivando su bloqueador de anuncios. ¡Gracias!</div>');
	  ; }, 5000);
	}
</script>
```

Filter - `9cartoon.me##script:inject(setTimeout-defuser.js, #player)`

**Comment by ghajini** [comment]
Fixed by ublock origin

**Comment by jspenguin2017** [comment]
Oh, awesome.

**Comment by jspenguin2017** [comment]
Yep, it works now. Thanks to everyone who worked on this.

**Comment by uBlock-user** [comment]
Did you add it to the List ?

**Comment by jspenguin2017** [comment]
No, looks like a uBO filter fixed it.

**Comment by uBlock-user** [comment]
Oh yeah, gorhill blocked the inline-script via the filter, that will do it too.

**Comment by uBlock-user** [comment]
Actually blocking inline-script breaks few things - https://github.com/uBlockOrigin/uAssets/commit/7ef368a2ca054c5ce10a50636ada3ea55ec1f4e4

**Comment by jspenguin2017** [comment]
Looks like you already commented on that commit, we'll wait a bit for their response before overriding their rule ourselves.

**Comment by uBlock-user** [comment]
Yes I did, he's the only one who can remove the filter, so providing him with feedback is better.

**Comment by jspenguin2017** [comment]
@uBlock-user We can override it with our rules though.

**Comment by uBlock-user** [comment]
Yes I know, but what I meant is I wouold prefer to have it removed from the uBlock Filters itself, wouldn't wanna create a `$badfilter` for this one.

**Comment by uBlock-user** [comment]
@jspenguin2017 Done - https://github.com/uBlockOrigin/uAssets/commit/dc6911aa80d8ec81148d6d67062c13d919c57453
