### ISSUE TITLE
al.ly

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/AdBlockProtector#200]
`ally.sh` is working, but apparently that domain has different code as `al.ly`. The button gets stuck on "Please wait..."

Test link: http://al.ly/Pnsvt

**Comment by ghajini** [comment]
You are doing awesome work,don't left project like @reek.......nice project

**Comment by uBlock-user** [comment]
Mine stays stuck at "Skip this ad"

**Comment by jspenguin2017** [comment]
The icon keeps turning, seems like it is waiting for something... 
![image](https://cloud.githubusercontent.com/assets/7283682/26037525/d1e2a348-38b1-11e7-9432-ec1e7beeb79c.png)

**Comment by jspenguin2017** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/26038933/aa4aad98-38d0-11e7-83d7-42f436fb722f.png)
![image](https://cloud.githubusercontent.com/assets/7283682/26038935/c34d85fe-38d0-11e7-86db-920ddc170591.png)
uBO's `popads.net.js` is not properly executed, but I don't think that is the cause of the button being stuck...

**Comment by jspenguin2017** [comment]
Oh wait, looks like removing the disabled property ourselves works 😮

**Comment by jspenguin2017** [comment]
reCaptcha is VERY not happy, I guess it's time to chill. This is the diff, I tested once. 
![image](https://cloud.githubusercontent.com/assets/7283682/26040030/b0bea694-38de-11e7-9276-e340be8c671b.png)

**Comment by jspenguin2017** [comment]
Finally cleaned up all the issues... Time to get my server online...

**Comment by lain566** [comment]
@jspenguin2017 remove this rule, 

`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=al.ly`


![ublock _ _registro_de_peticiones_de_red_-_google_c_2017-05-15_10-52-25](https://cloud.githubusercontent.com/assets/27441315/26049940/20c5f18a-395d-11e7-86ec-b24f204e310d.png)

**Comment by jspenguin2017** [comment]
Hum... yea... Looks like that's the source of the issue... Thanks.
