### ISSUE TITLE
mmo-champion.com

### ISSUE THREAD

**Issue by rognarok** [jspenguin2017/AdBlockProtector#203]
It has a anti adblock popup every day or so now, if you are running a adblocking addon, such as ublock origin It's powered by Admiral I guess.  Just going to the front page should be enough to see the popup

**Comment by jspenguin2017** [comment]
`||broadcastbed.com^$domain=mmo-champion.com`

**Comment by jspenguin2017** [comment]
Seems to work for me. Added to List.

**Comment by uBlock-user** [comment]
Block third-party script rather as the domain will change every few days.

**Comment by jspenguin2017** [comment]
Yea... I guess...

**Comment by jspenguin2017** [comment]
That is blocking a bit too much... It will cost them $10 each time they register a domain, but 5 seconds for us to patch it, I guess it's fine.

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing this issue. 
Let me know if it breaks again.
