### ISSUE TITLE
uk.businessinsider.com

### ISSUE THREAD

**Issue by xtrah69** [jspenguin2017/AdBlockProtector#204]
Adguard Desktop 6.1: Adblock Protector Script and Filter.

Ublock user was unable to reproduce the issue as he said it's been resolved yet I'm still getting it. I've even tried running Tampermonkey but it makes no difference.

![image](https://cloud.githubusercontent.com/assets/24882469/26037952/046966be-38f6-11e7-8172-7a273728974e.png)

![image](https://cloud.githubusercontent.com/assets/24882469/26037957/0dcfa2a4-38f6-11e7-94e8-fdcceab1eb49.png)

Seems to be active and working correctly...

Problem pops up on any article: http://uk.businessinsider.com/flux-app-review-2015-12?r=US&IR=T

**Comment by jspenguin2017** [comment]
I don't see anything wrong with this website. Can you try uBlock Origin instead of Adguard? 
![image](https://cloud.githubusercontent.com/assets/7283682/26038275/3442be00-38c2-11e7-848e-2ce7075f5dde.png)

**Comment by jspenguin2017** [comment]
I have updated List installation test, it is now using a syntax that Adguard can't handle (as of now).

**Comment by uBlock-user** [comment]
Already patched in uBO. Adguard is not a part of the supported setup.

uBO Filter - `||npttech.com/advertising.js$important,script`

**Comment by xtrah69** [comment]
I see, thank you.

**Comment by xtrah69** [comment]
Rule was given to me by Blaz on the Adguard forums:
businessinsider.com$$script[tag-content="window["mzm1zd"]"]

Works for the Adguard users, may want to consider adding it into the script?

**Comment by jspenguin2017** [comment]
@xtrah69 As we said before, it is already fixed by Script.

**Comment by jspenguin2017** [comment]
@xtrah69 I think that filter only work on Adguard proxy, and I don't see why should I consider adding it since it is already fixed elsewhere.
