### ISSUE TITLE
afreesms.com

### ISSUE THREAD

**Issue by azuretbn** [jspenguin2017/AdBlockProtector#205]
http://www.afreesms.com/intl/philippines

I am using the standard setup. 
[Screenshot of the page after a few seconds of standby.
](http://prntscr.com/f7yf6i)

**Comment by uBlock-user** [comment]
filter -` afreesms.com##script:inject(noeval.js)`

**Comment by jspenguin2017** [comment]
@uBlock-user 👍

**Comment by uBlock-user** [comment]
Did you add the filter to the list ?

**Comment by jspenguin2017** [comment]
Yes I did.

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing this issue.
Let me know if it breaks again.
