### ISSUE TITLE
translatica.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#207]
same adblock as on pwn.pl

![capture](https://cloud.githubusercontent.com/assets/15007183/26054295/01b9ed5a-393a-11e7-9543-cdfaca8a9105.PNG)

**Comment by xxcriticxx** [comment]
i think @uBlock-user gave to you because it got passed your generic filters 

from the pl list:
`@@||translatica.pl/ads.js$script`

**Comment by jspenguin2017** [comment]
Seems to work. Added to Script.

**Comment by uBlock-user** [comment]
No I didn't give any filter for this case. Secondly, that whitelisting filter is generic and should not be used as it provides an opportunity for the webmaster to abuse.

**Comment by xxcriticxx** [comment]
well my guess was wrong sorry

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing this issue.
Let me know if it breaks again.
