### ISSUE TITLE
windowscentral.com

### ISSUE THREAD

**Issue by kevin12314** [jspenguin2017/AdBlockProtector#210]
Link：
http://www.windowscentral.com/

![image](https://cloud.githubusercontent.com/assets/10508800/26114778/d1976582-3a90-11e7-8a9b-de8f0644e8a8.png)

**Comment by jspenguin2017** [comment]
Can you try to update your filters? It could be they are using multiple scripts on server side... 
![image](https://cloud.githubusercontent.com/assets/7283682/26115398/20172b58-3a1d-11e7-815e-49721e5c21c3.png)

**Comment by dmo580** [comment]
Personally testing on my end as I was reading an article there. The main page loaded just fine but once I clicked on an article I got the issue shown above.

**Comment by ghajini** [comment]
Yes seen antiadblock at homepage powered by `Admiral`
![img_20170516_215704](https://cloud.githubusercontent.com/assets/20338483/26117355/e1aa21a6-3a83-11e7-99ae-6c2d170f1d65.JPG)

**Comment by jspenguin2017** [comment]
Can you guys log the domain that serves Admiral script?

**Comment by ghajini** [comment]
Iam on android,I can't help sorry

**Comment by uBlock-user** [comment]
They have two anti adblock scripts, one third party and one inline, blocking 3rd party only won't help.

**Comment by jspenguin2017** [comment]
@uBlock-user Thanks for the info, I'll investigate.

**Comment by szymon1118** [comment]
`a.filter("setTimeout");` works for me

**Comment by uBlock-user** [comment]
This is the 3rd or the 4th time they have evaded. A hardened solution is in order.

**Comment by uBlock-user** [comment]
@szymon1118 That breaks thumbnails and Show Me More button.

**Comment by uBlock-user** [comment]
Anti adblock script - https://gist.githubusercontent.com/uBlock-user/c520543d6fad1545f8803203c16352e3/raw/e2bc57fdf8f7df456151d67311c7bbe2b3684cd9/gistfile1.txt

**Comment by ghajini** [comment]
Can we block `admiral` just like blockadblock/fuckadblock

**Comment by uBlock-user** [comment]
Nevermind, it was Easylist's filter that was breaking the top two thumbnails and the Show Me More button.

Killing all setTimeout calls works fine.

**Comment by uBlock-user** [comment]
List of websites affected  - `androidcentral.com, windowscentral.com, crackberry.com, imore.com`

BadFilters  - 

```
||windowscentral.com/sites/wpcentral.com/files/advagg_js/$script
||imore.com/sites/imore.com/files/advagg_js/$script
||crackberry.com/sites/crackberry.com/files/advagg_js/$script
```

**Comment by Zhangsun321** [comment]
how/where do i add the a.filter("setTimeout");?
do I add the 'bad filters' to the my filters list?
ty

**Comment by szymon1118** [comment]
@Zhangsun321 It's only an example solution. I think we need to wait for @jspenguin2017 to check if it's good and implement it to userscript.

**Comment by Zhangsun321** [comment]
ooh ok...    well let me take the time to say thank you to everyone for what you do..
i know absolutely nothing bout javascript, or i would help 'sniff out' the blocks..   
all i do on twitter is help people find this place...  so i hope use skyrockets someday :)

**Comment by jspenguin2017** [comment]
Thanks for the info, can someone log `setTimeout`? I have some slight issues with something else and I'm a bit busy today.

**Comment by uBlock-user** [comment]
here you go - https://gist.githubusercontent.com/uBlock-user/4f40c133c88cf13a72d2c85800a7c3e7/raw/2fb83b50d77037c1bca109c24309e492010274e5/gistfile1.txt

**Comment by uBlock-user** [comment]
@Zhangsun321 This is all part of the investigation and discussion, nothing is to be added anywhere.

**Comment by jspenguin2017** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/26122935/629f83c6-3a36-11e7-8d86-348ada5c4ed3.png)
Does blocking only this works?

**Comment by uBlock-user** [comment]
What would be the name of the setTimeout call there ?

**Comment by ghajini** [comment]
This 1 is found in adguard filters
for antiadblock
`androidcentral.com,chicagoreader.com,crackberry.com,imore.com,onmsft.com,thewindowsclub.com,windowscentral.com#%#(function(a,e,d){a&&(Promise=function(b){if("function"!=typeof b)throw new TypeError(b+ " is not a function");for(var f=e.call(b),c=0,g=d.length;c<g;c++)if(d[c][0].test(f))return d[c][1]?a.reject(d[c][2]):a.resolve(d[c][2]);return new a(b)},Object.getOwnPropertyNames(a).forEach(function(b){Object.defineProperty(Promise,b,Object.getOwnPropertyDescriptor(a,b))}),a.prototype.constructor=Promise)})(Promise,Function.prototype.toString,[[/MozBinding\.indexOf\("abp[\s\S]*?\.displayNoneImportant\)/],[/\.parentNode\.removeChild\([\s\S]*?\.removeEventListener\("error"[\s\S]*?\.createElement\([\s\S]*?\.getElementsByTagName\("head"/,,1],[/\.createElement\("iframe"[\s\S]*?URL\.createObjectURL\(new Blob\(\[""/],[/\.displayNoneImportant[\s\S]*?tpc\.googlesyndication[\s\S]*?\.addEventListener\(["']message["']/,1]]);
sanfoundry.com#%#(function(a,e,d){a&&(Promise=function(b){if("function"!=typeof b)throw new TypeError(b+ " is not a function");for(var f=e.call(b),c=0,g=d.length;c<g;c++)if(d[c][0].test(f))return d[c][1]?a.reject(d[c][2]):a.resolve(d[c][2]);return new a(b)},Object.getOwnPropertyNames(a).forEach(function(b){Object.defineProperty(Promise,b,Object.getOwnPropertyDescriptor(a,b))}),a.prototype.constructor=Promise)})(Promise,Function.prototype.toString,[[/MozBinding\.indexOf\("abp[\s\S]*?\.displayNoneImportant\)/],[/\.parentNode\.removeChild\([\s\S]*?\.removeEventListener\("error"[\s\S]*?\.createElement\([\s\S]*?\.getElementsByTagName\("head"/,,1],[/\.createElement\("iframe"[\s\S]*?URL\.createObjectURL\(new Blob\(\[""/],[/\.displayNoneImportant[\s\S]*?tpc\.googlesyndication[\s\S]*?\.addEventListener\(["']message["']/,1]]);`

`windowscentral.com#@#.adunit`

**Comment by uBlock-user** [comment]
This works - `windowscentral.com##script:inject(setTimeout-defuser.js, [native code])`

**Comment by jspenguin2017** [comment]
Native code?! 
A function that is native, without argument, can do the detection job?! Is `toString()` patched? 

@ghajini 
```JavaScript
(function(a, e, d) {
    a && (Promise = function(b) {
        if ("function" != typeof b) throw new TypeError(b + " is not a function");
        for (var f = e.call(b), c = 0, g = d.length; c < g; c++)
            if (d[c][0].test(f)) return d[c][1] ? a.reject(d[c][2]) : a.resolve(d[c][2]);
        return new a(b)
    }, Object.getOwnPropertyNames(a).forEach(function(b) {
        Object.defineProperty(Promise, b, Object.getOwnPropertyDescriptor(a, b))
    }), a.prototype.constructor = Promise)
})(Promise, Function.prototype.toString, [
    [/MozBinding\.indexOf\("abp[\s\S]*?\.displayNoneImportant\)/],
    [/\.parentNode\.removeChild\([\s\S]*?\.removeEventListener\("error"[\s\S]*?\.createElement\([\s\S]*?\.getElementsByTagName\("head"/, , 1],
    [/\.createElement\("iframe"[\s\S]*?URL\.createObjectURL\(new Blob\(\[""/],
    [/\.displayNoneImportant[\s\S]*?tpc\.googlesyndication[\s\S]*?\.addEventListener\(["']message["']/, 1]
]);
sanfoundry.com# % #(function(a, e, d) {
    a && (Promise = function(b) {
        if ("function" != typeof b) throw new TypeError(b + " is not a function");
        for (var f = e.call(b), c = 0, g = d.length; c < g; c++)
            if (d[c][0].test(f)) return d[c][1] ? a.reject(d[c][2]) : a.resolve(d[c][2]);
        return new a(b)
    }, Object.getOwnPropertyNames(a).forEach(function(b) {
        Object.defineProperty(Promise, b, Object.getOwnPropertyDescriptor(a, b))
    }), a.prototype.constructor = Promise)
})(Promise, Function.prototype.toString, [
    [/MozBinding\.indexOf\("abp[\s\S]*?\.displayNoneImportant\)/],
    [/\.parentNode\.removeChild\([\s\S]*?\.removeEventListener\("error"[\s\S]*?\.createElement\([\s\S]*?\.getElementsByTagName\("head"/, , 1],
    [/\.createElement\("iframe"[\s\S]*?URL\.createObjectURL\(new Blob\(\[""/],
    [/\.displayNoneImportant[\s\S]*?tpc\.googlesyndication[\s\S]*?\.addEventListener\(["']message["']/, 1]
]);
```

**Comment by jspenguin2017** [comment]
Oh wait, Promise... That makes sense...

**Comment by uBlock-user** [comment]
@jspenguin2017 Gorhill used it as a filter for `thewindowsclub.com` you can check it here - `chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=ublock-filters`

**Comment by jspenguin2017** [comment]
Ah I see. Does that fixes it?

**Comment by uBlock-user** [comment]
Updated the link, I need a confirmation from you, works on my side.

**Comment by jspenguin2017** [comment]
OK, I'll test later. Thanks.

**Comment by Zhangsun321** [comment]
windowscentral.com##script:inject(setTimeout-defuser.js, [native code])  works for me..

**Comment by uBlock-user** [comment]
FYI `thewindowsclub.com` was also using Anti Adblock script from Admiral.

**Comment by jspenguin2017** [comment]
That is blocked by EasyList I think.

**Comment by uBlock-user** [comment]
I don't know, but the script is same.

**Comment by ghajini** [comment]
@seanl-adg can help who created this filter in adguard for that site

**Comment by uBlock-user** [comment]
@jspenguin2017 Patching Promise breaks Show Me More

**Comment by jspenguin2017** [comment]
@ghajini I know what that filter does, it just filter arguments from `Promise`. 
@uBlock-user Thanks, if uBO filter patched it, we can call this one solved?

**Comment by jspenguin2017** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/26124881/5d2aea0a-3a3d-11e7-9833-9f26b0072c47.png)
We need to patch jQuery, now we have a jQuery loader built in: `a.win.$ = a.win.jQuery = a.make$()`

**Comment by seanl-adg** [comment]
Hi all,

It is similar to the case of IL, the quick `Promise` wrapper defuses admiral's detection logic.
Admiral's code performs various checks to detect adblockers, and each regular expressions is supposed to defuse a corresponding check. You see, the admiral's adblock detection code internally stores a value named `hasAdblockerScore`; by defusing, the value becomes 0.

You don't necessarily wrap `Promise`, I deem filtering `setTimeout` with `[native code]` ok, but you should provide the timeout number in order to make it safer.

Also, please note that site breakages including missing `jQuery` and broken buttons are completely unrelated to the blocker's javascript patches. They are broken due to EasyList's aggressive blocking rules.

**Comment by okiehsch** [comment]
@jspenguin2017 FYI https://github.com/uBlockOrigin/uAssets/commit/37fd3aaf86614be1cc2c6d962f26cbef180fd1e3

**Comment by okiehsch** [comment]
Changed the fix https://github.com/uBlockOrigin/uAssets/commit/315c0b7fc65f06bd01d4c13f787f3577c8ebe2dd
Explanation https://github.com/uBlockOrigin/uAssets/commit/37fd3aaf86614be1cc2c6d962f26cbef180fd1e3#commitcomment-22166146

**Comment by jspenguin2017** [comment]
@okiehsch Thanks for your hard work. I'll update filters and test everything out when I have time tomorrow.

**Comment by uBlock-user** [comment]
@jspenguin2017 gorhill's filter also patched it! Works as expected.

**Comment by jspenguin2017** [comment]
Awesome! This is patched by filters! Good job everyone!

**Comment by jspenguin2017** [comment]
Looks like it's still working, closing. 
Let me know if something breaks again.
