### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#218]
@jspenguin2017 can you please add this. this gets this gets rid of left and right side movie recommendations. any other form of code in this matter is greatly appreciated.

code possible thx to user @F4z

```
if (a.domCmp(["cda.pl"])) {
    a.readOnly("adblockV1", true);
}
```

![capture](https://cloud.githubusercontent.com/assets/15007183/26258062/09394422-3c91-11e7-944c-a549f0e98296.PNG)

**Comment by jspenguin2017** [comment]
Added to Script.

**Comment by uBlock-user** [comment]
OR

two cosmetic filters can also take care of it

```
cda.pl##.muimErPIa
cda.pl##.muimERPIa
```

**Comment by xxcriticxx** [comment]
@uBlock-user name changes every few days

**Comment by xxcriticxx** [comment]
@jspenguin2017 thx

**Comment by uBlock-user** [comment]
@xxcriticxx 

there you go

```
cda.pl##.boIk-left
cda.pl##.bolk-right
```
That covers the entire left and right banner.

**Comment by xxcriticxx** [comment]
next week that will change to boik-lefT or something else 

@F4z cane out with this:

`cda.pl##a[class][target]:has(img[src*="premium"])`

or 

`cda.pl##script:inject(abort-on-property-read.js, adblockV1)`

or the code from the first post

**Comment by jspenguin2017** [comment]
Yea, locking `adblockV1` seems to be the best for now, they can rename it to `adblockV2` etc, which can be a pain to deal with, blocking image with source that has "premium" in it might not be that safe, but let's keep it in mind in case we need it.

**Comment by uBlock-user** [comment]
Then you will just have to find something they can't change, that will throw them off.

**Comment by xxcriticxx** [comment]
can you put `adblock*` would this work in that filter?

**Comment by jspenguin2017** [comment]
@xxcriticxx No, you can't declare variable like that...

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing. Let me know if something is not right.
