### ISSUE TITLE
viki.com

### ISSUE THREAD

**Issue by guoqiyun** [jspenguin2017/AdBlockProtector#219]
`/\.viki\.io\/[a-z]\/[0-9]+/$script,domain=viki.com`

**Comment by jspenguin2017** [comment]
Can you explain what's wrong with this website? 
![image](https://cloud.githubusercontent.com/assets/7283682/26272018/d01da4c2-3ccb-11e7-9e99-b8c1882b4ccc.png)

**Comment by guoqiyun** [comment]
If you do not block it, videos get paused for about five seconds when they normal show ads. As you may be able to imagine, it is very intrusive to viewers. The characters in URL change every so often hence the regex used in the rule.

https://github.com/reek/anti-adblock-killer/issues/2990

**Comment by jspenguin2017** [comment]
Can you tell me when does it "normally show ads"? 

Test page: https://www.viki.com/videos/1117889v-suspicious-partner-episode-8

**Comment by jspenguin2017** [comment]
I don't see the script being requested, can you dump the code of one sample script? 
![image](https://cloud.githubusercontent.com/assets/7283682/26272571/e38ef828-3cd8-11e7-99d0-d2c8132f62cf.png)

**Comment by uBlock-user** [comment]
Another Geo-Locked website - 

![](https://i.gyazo.com/b560b8b3c87e87621525199a6297e494.png)

**Comment by uBlock-user** [comment]
This video is not Geo-Locked apparently - https://www.viki.com/videos/44699v-boys-over-flowers-episode-1

Can't reproduce any ads.

**Comment by uBlock-user** [comment]
Blocking connections to `viki.io` should it if you can reproduce it. 

`||viki.io^$domain=viki.com`

**Comment by xxcriticxx** [comment]
this comes up for me and pauses the vid

![capture](https://cloud.githubusercontent.com/assets/15007183/26275192/4c18ae7a-3d29-11e7-9202-f875de72cd99.PNG)

![capture2](https://cloud.githubusercontent.com/assets/15007183/26275209/9de656b2-3d29-11e7-91d3-5e30996db98a.PNG)
![capture5](https://cloud.githubusercontent.com/assets/15007183/26275210/a0fed5f4-3d29-11e7-9cbc-2c1c65338510.PNG)

**Comment by uBlock-user** [comment]
So it appears it only happens if you have Flash player.

**Comment by xxcriticxx** [comment]
they have adds because they sell ads free pass. they also have system that ads posts from the forum on top. 


![capture](https://cloud.githubusercontent.com/assets/15007183/26275267/af8065ce-3d2a-11e7-932e-68ec8b4d3395.PNG)

**Comment by uBlock-user** [comment]
Ads don't load for me, but there's flash detection in your logs which is not happening on my end.

**Comment by xxcriticxx** [comment]
i dont have ads either i just get few stupid pop ups to buy ads free pass and language feature

**Comment by jspenguin2017** [comment]
@xxcriticxx I think that is Danmaku, you don't want to block that.

**Comment by ghajini** [comment]
@guoqiyun, did you tried filters from easylist these one

`@@||viki.com^$generichide`
`@@||1.viki.io/cms-uploads/uncategorized/ima3.js`
`@@||imasdk.googleapis.com^$domain=viki.com`

**Comment by guoqiyun** [comment]
@jspenguin2017 Please have a look the thread at AAK’s GitHub which I linked before. It includes a screenshot by brainkk: https://puu.sh/uVL2I/b86a88e222.png. It occurs many times (~15 minutes) throughout all videos but not always. You may have to watch a full episode to be able to replicate it. Here is an example: http://1.viki.io/a/19610704-4a40ca1279980d6b1f06a1c0c5e0cef1.js. The characters in the URL change every x days.

Please ignore @xxcriticxx and @uBlock-user. Their information is completely unrelated to this problem.

@ghajini Thanks for your input, but I already use the latest EasyList and EasyList China; they block ads just fine. My rule stops Viki’s intrusive ad block detector which does not appear to be blocked by AdBlockProtector list.

**Comment by jspenguin2017** [comment]
@guoqiyun Can you install AdBlock Protector Script and test it? That example script should be neutralized by our generic solutions: 
![image](https://cloud.githubusercontent.com/assets/7283682/26280856/ba7c660a-3da0-11e7-961d-f2b4248fae6a.png)

**Comment by jspenguin2017** [comment]
The unminified code: 
```JavaScript
! function(t) {
    var n = function(t) {
            this._options = {
                baitUri: null
            }, void 0 !== t && this.setOption(t)
        },
        o = [function() {
            return new XMLHttpRequest
        }, function() {
            return new ActiveXObject("Msxml3.XMLHTTP")
        }, function() {
            return new ActiveXObject("Msxml2.XMLHTTP")
        }, function() {
            return new ActiveXObject("Microsoft.XMLHTTP")
        }];
    n.prototype._createXMLHTTPObject = function() {
        for (var t = !1, n = 0; n < o.length; n++) {
            try {
                t = o[n]()
            } catch (t) {
                continue
            }
            break
        }
        return t
    }, n.prototype._uriCheck = function(t, n) {
        var o = this._createXMLHTTPObject();
        return o ? (o.open("get", t, !0), o.onreadystatechange = function() {
            var t;
            4 == o.readyState && (t = o.status, n(200 == t ? !1 : !0))
        }, void o.send()) : void n(!1)
    }, n.prototype.setOption = function(t, n) {
        if (void 0 !== n) {
            var o = t;
            t = {}, t[o] = n
        }
        for (var e in t) this._options[e] = t[e];
        return this
    }, n.prototype.check = function(t) {
        this._options.baitUri ? this._uriCheck(this._options.baitUri, t) : t(!1)
    }, t.BlockAdBlock = n, void 0 === t.blockAdBlock && (t.blockAdBlock = new n)
}(window);
```

**Comment by guoqiyun** [comment]
@jspenguin2017 Thanks, that is great. I have started using the script now. I will try to spread the word when I can.

**Comment by uBlock-user** [comment]
@guoqiyun and how is my info unrelated ? I can't reproduce it and for that case neither can @jspenguin2017  and the information I provided is relevant given the fact that it doesn't show detection for everyone, not to mention there's also a Geo-Lock. Just because you can reproduce it doesn't make it a fact, it just happens to be one of the cases on your end.

**Comment by uBlock-user** [comment]
@jspenguin2017 I can reproduce it now after removing all cache and site data and it appears on the yellow spots on the player and puts an overlay so you can't see the episode but you can still see it.

Filter - `viki.com##.vkp-anti-ab`

**Comment by guoqiyun** [comment]
@uBlock-user 

Wow, someone is butthurt.

You were mentioning ‘Geo-Locked’, ‘ads’, ‘blocking connections’, ‘Flash Player’; none of these have anything to do with my thread. They are unrelated even to this project.

If you had read the full thread before your post, you would know I use EasyList and EasyList China already. The problem is the website being intrusive toward ad block users which this project is for. It has nothing to do with blocking ads; I would be posting to EasyList’s website if it were.

Finally, please learn to reply only when you have something valuable to add. No one would open a thread for nothing.

**Comment by uBlock-user** [comment]
Really ? Now, that's some kind of childish behavior after all. Closing the thread because you think you're right and done with the investigation and when someone else comes up with facts that you just can't accept ? Well good choice, that will save me my precious time too instead of relegating after someone who is not only ungrateful but simply doesn't understand what this repository is for in the first place.

> Finally, please learn to reply only when you have something valuable to add.

It's called an investigation, learn to read the repo contributing rules before you open the thread - https://github.com/jspenguin2017/AdBlockProtector/blob/master/CONTRIBUTING.MD#opening-an-issue which you simply didn't bother to do and just pasted a bad filter which will not only block scripts by random and but will break the player too, kudos to you for your imaturity, bravo!

**Comment by guoqiyun** [comment]
‘Childish’? I was surprised to see that @jspenguin2017 had not closed the thread already, so I did it with the intention to prevent further unnecessary (and confusing) replies from appearing. Also, how does closing the thread have anything to do with me thinking I am right? If you had read the full thread (once again), you will find that there is another (better) solution by the project owner.

You are only embarrassing yourself at this point. I suggest you stop here before you lose even more face. I just love seeing you edit your replies trying to make yourself look better!

**Comment by jspenguin2017** [comment]
Let's lock this thread. The conversation is not constructive.
