### ISSUE TITLE
temp-mail.org

### ISSUE THREAD

**Issue by guoqiyun** [jspenguin2017/AdBlockProtector#220]
`||temp-mail.org/js/antiblock.js$script,domain=temp-mail.org`

**Comment by jspenguin2017** [comment]
This was fixed by Script a while ago. See #174

**Comment by guoqiyun** [comment]
‘Fixed’ where? I am unable to find ‘temp-mail.org’ in https://raw.githubusercontent.com/jspenguin2017/AdBlockProtector/master/AdBlockProtectorList.txt

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/AdBlockProtector/blob/master/AdBlockProtector.user.js#L2841
![image](https://cloud.githubusercontent.com/assets/7283682/26272527/fc551d70-3cd7-11e7-9e47-28047fffe076.png)

**Comment by uBlock-user** [comment]
Most of the solutions are patched in Script, so look for that first.

**Comment by jspenguin2017** [comment]
Looks like everything is good? Closing this issue then.

**Comment by guoqiyun** [comment]
@jspenguin2017 Yes, I was not aware you had a script too. I think it would still be better to include a normal rule instead for people who do not want or know how to use your script. Since there is no regex involved, it should be lightweight if one uses uBlock Origin extension. I am sure most users simply enable certain filters from extension’s settings like I did.

**Comment by jspenguin2017** [comment]
@guoqiyun No, this project has two parts: List and Script, they work tightly together. Only using List will only cause more problem since it's not rare that we use List to break a website so Script can fix it later without interference.

**Comment by guoqiyun** [comment]
@jspenguin2017 OK, thanks. I will start using the script now.

**Comment by jspenguin2017** [comment]
@guoqiyun https://github.com/gorhill/uBlock/issues/2634

**Comment by guoqiyun** [comment]
@jspenguin2017 That is great, Sir. It would avoid many unnecessary threads on here.

**Comment by jspenguin2017** [comment]
TBH I'm not sure if our algorithm is that much faster than good RegExp, since function calls are also expensive. It is just a lot simpler to code since in RegExp, `.` means "match everything except new line" which is kind of a pain since there are literal `.` in pretty much every domain. 
AAK doesn't take this into account, and it is missing anchors, which means their domain matching is flawed and slowed at the same time. Also their solutions are arranged in functions, and dead code can't be efficiently garbage collected since the whole object's reference is held.

**Comment by guoqiyun** [comment]
@jspenguin2017 Yes, I could see where you are coming from regarding regex.

There is no doubt relying solely on the filter would wrongly break websites from time to time which your solution avoids while taking possible changes by websites in account. The project is not bad. I am sure users would not mind a small but unnoticeable performance hit in exchange for stability.
