### ISSUE TITLE
community.steamcustomizer.com

### ISSUE THREAD

**Issue by Connor37** [jspenguin2017/AdBlockProtector#223]
http://community.steamcustomizer.com/explore

![image](https://cloud.githubusercontent.com/assets/8341213/26284359/2cba7192-3e39-11e7-8303-7a420461d87b.png)

**Comment by uBlock-user** [comment]
Try 

```
steamcustomizer.com###sadcat
steamcustomizer.com##.notice.support-notice
```

**Comment by jspenguin2017** [comment]
One of the thumbnails goes through `/skin/ad/` directory, that seems to be the only resource that go though it, so I'll white list it. 
`@@||steamcustomizer.com/cache/skin/ad/*$image`

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing.
