### ISSUE TITLE
nflix.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#225]
test link:

https://www.nflix.pl/kategoria/netflix-pl/

![capture](https://cloud.githubusercontent.com/assets/15007183/26284091/2900d9b6-3e01-11e7-8fea-f545e56c4462.PNG)

add this domain here info thx to @F4z

```
if (a.domCmp(["gametransfers.com", "winandmac.com", "free-steam-giveaways.com", "canalwp.com",
    "alphahistory.com", "nordpresse.be", "sospc.name", "baboo.com.br"])) {
    a.always(function () {
        a.cookie("anCookie", "true");
        a.win.anOptions = {};
    });
}
```

**Comment by jspenguin2017** [comment]
Looks like that works. Thanks.

**Comment by uBlock-user** [comment]
`@@||nflix.pl^$elemhide` will also work, the script inserts Easylist classes and baits the user, so disabling generic classes insertion puts an end nicely without having to create any cookie for them to check.

**Comment by jspenguin2017** [comment]
@uBlock-user That's not good, even though ads don't load, the place holders are annoying: 
![image](https://cloud.githubusercontent.com/assets/7283682/26286282/85c8d1d6-3e1e-11e7-9d5e-df8f5fff398c.png)

**Comment by uBlock-user** [comment]
@jspenguin2017 I know and you can thank Easylist for that, instead of adding individual domain(s) per cosmetic filter, they made all major filters generic, so if you use `$elemhide`, you will have to block placeholders manually by creating cosmetic filters for the domain in question.

**Comment by jspenguin2017** [comment]
@uBlock-user It's too much work to manually check each website for which placeholder they have. They had to make it generic. You don't want the 70k lines of rules to become 700k.

**Comment by uBlock-user** [comment]
No, not for all classes, some them are not as commonly used as `##.adsbygoogle`. I can assure you that. I have ran uBO logger for a long time to conclude that some classes which are rarely used such as `##.fb-xfbml-parse-ignore` were also made generic. That one is the first time I have seen and is not commonly used. They could have made it specific if they wanted to.

Also speaking on 70k lines of rule become 700k, it won't happen if you simply add the domains collectively before  ## like we did for -  #224 Then you will only have one line with all the domain specific to that cosmetic filter.

**Comment by jspenguin2017** [comment]
@uBlock-user Yea, the things is EasyList is doing the heaviest lifting, they probably don't have that much resource to make every solution ideal.

**Comment by uBlock-user** [comment]
Anyways, someone has to do the heavy lifting once, on another note, making generic cosmetic filters also implications in the name of performance, ABP is slow compared to uBO as this is one of the reasons. It has to inserts 65000+ CSS selectors and that kills the performance of the browser itself. This is why avoid making cosmetic filters generic as possible.

**Comment by jspenguin2017** [comment]
@uBlock-user That once is already too much 😂 Going over 70k lines of code and scan the whole Internet to see how to handle those generic rules... Even with a solid script it's still no go since scraping whole internet is VERY different than scraping 100 pages.

**Comment by uBlock-user** [comment]
I never said scan the whole Internet 😆 , just keeping on adding the domains you come across, that's it. Easylist guys just don't want to do that either and simply add one filter for all and patch it forever solution.

**Comment by jspenguin2017** [comment]
I... don't really want to get into that... It will become a pain real quick.
