### ISSUE TITLE
chiaanime.co

### ISSUE THREAD

**Issue by gavbn** [jspenguin2017/AdBlockProtector#226]
Hi,it's not working on:
"http://chiaanime.co/Watch/20008/bleach-2004-2012/episode-324"

**Comment by jspenguin2017** [comment]
OK, I'll have a look.

**Comment by uBlock-user** [comment]
`chiaanime.co##script:inject(setTimeout-defuser.js, #player)`

**Comment by uBlock-user** [comment]
same as others

```javascript
if(document.getElementById('dKXaJTLMrRmZ')){
	} else {
	  setTimeout(function(){ 
		$('#player').html('<div style="text-align: center;padding-top: 200px;font-size: 20px;line-height: 28px;">Our site is maintained by ads on the site, please help us keep it going by turning off your adblock. Thank you!</div>');
	  ; }, 5000);
```

**Comment by jspenguin2017** [comment]
OK, thanks, I combined all the domains together.

**Comment by gavbn** [comment]
the filter breaks the flash player option
![capture](https://cloud.githubusercontent.com/assets/23123477/26285958/9e0a9e24-3e77-11e7-81d6-e9f462f5d82e.PNG)

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://cloud.githubusercontent.com/assets/7283682/26286024/9eea5ef6-3e18-11e7-8ef9-34d9b94e91eb.png)

**Comment by gavbn** [comment]
here is the link for the issue:
"http://chiaanime.co/Watch/164575/one-piece-subbed/episode-789"

**Comment by jspenguin2017** [comment]
The flash player there doesn't work at all. 
![image](https://cloud.githubusercontent.com/assets/7283682/26286081/6c62deee-3e19-11e7-9160-2d6f57bf1c82.png)

**Comment by gavbn** [comment]
Ok,thanks for the quick support

**Comment by uBlock-user** [comment]
The filter doesn't break anything except the timeout call specifically sent from the anti adblock script, I can guarantee you that. The website itself is badly coded or cloned from many other badly coded clones.
