### ISSUE TITLE
new-skys.net

### ISSUE THREAD

**Issue by uBlock-user** [jspenguin2017/AdBlockProtector#227]
Test-link - http://new-skys.net/dragon-city

Shows an alert and redirects you to the homepage on detection

Anti adblock script

```javascript
$(document).ready(function(){
	function TestPage2() {
		if ($('.myadsCheck').height() ==0){
			alert("You are blocking my beautiful adverts, please turn on it!");
			window.location.href="http://new-skys.net";
		}
	}

	$(TestPage2);
	});
```

Solution - `a.bait("div", ".myadsCheck");`

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/3233

**Comment by Dibbyo456** [comment]
@uBlock-user @jspenguin2017 Do you have a email? I would like to have some disqus with you guys.

**Comment by uBlock-user** [comment]
Discuss what ?

**Comment by jspenguin2017** [comment]
@uBlock-user Thanks, I'll add it to Script. 

@Dibbyo456 Hi, please open an issue if you have something that you want me to know.

**Comment by Dibbyo456** [comment]
I want to learn how defeat Adblocker & AdBlock Protecter o Reek's scripts or something like those. 
I know this is last place to ask such kind of things, but you guys know the flaw, so it's better to ask you guys. 
I use pure Adsense, so any advice?

**Comment by uBlock-user** [comment]
> I want to learn how defeat Adblocker & AdBlock Protecter o Reek's scripts or something like those.

That's irony in itself 🤣 

@jspenguin2017 On second thought, we can kill `location.href` and `alert` too via these filters. Though I'm unsure if blocking `location.href` will break anything.

```
new-skys.net##script:inject(abort-on-property-read.js, location.href)
new-skys.net##script:inject(alert-buster.js)
```

**Comment by jspenguin2017** [comment]
@Dibbyo456 Our source code is open, and it is rather easy to defeat. How to do that specifically? Well, you got to figure that out yourself. 

@uBlock-user I'm pretty sure `location.href` can't be redefined.

**Comment by uBlock-user** [comment]
@jspenguin2017 So will it break the website  functionality ? The filter works, add those filters and see for yourself

**Comment by jspenguin2017** [comment]
@uBlock-user No, it just do nothing: 
![image](https://cloud.githubusercontent.com/assets/7283682/26316030/300eb2c6-3ed0-11e7-80aa-755ae568e7d2.png)

**Comment by uBlock-user** [comment]
> Patching alert is enough.

That doesn't stop the redirection which is the core issue here, only alert is killed.

**Comment by uBlock-user** [comment]
`abort-on-property-read.js`, doesn't set value, it restricts the variable from being read similar to what `a.noAccess` does.

**Comment by jspenguin2017** [comment]
@uBlock-user 
It definitely will stop redirection as alert throws an error and the function aborts. 
In order to restrict variable read, it needs to redefine it.

**Comment by uBlock-user** [comment]
Doesn't happen on my end untill I add `a.noAccess("location.href");`

**Comment by jspenguin2017** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/26316636/2835d456-3ed2-11e7-8f99-1e9ce0dc0f29.png)

**Comment by uBlock-user** [comment]
Hmmm, probably because I'm on a slow connection today, so results are not appearing as intended. But you're right about `location.href` being failed to define.

**Comment by jspenguin2017** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/26316846/cbd7c36c-3ed2-11e7-893a-2a5c18d0d082.png)
`alert-buster` does not restrict property access, use `abort-on-property-read` on `alert` instead.

**Comment by uBlock-user** [comment]
Thanks, closing the issue.
