### ISSUE TITLE
linkneverdie.com

### ISSUE THREAD

**Issue by LaxusiC** [jspenguin2017/AdBlockProtector#229]
It doesn't work on this site, could you please fix :)

http://prntscr.com/fazub0

**Comment by jspenguin2017** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/26337445/ff0d7962-3f35-11e7-86c1-cdef0237bc0b.png)
Works for me.

**Comment by LaxusiC** [comment]
Sorry but it's work now O_O. I chose the filter in Adguard settings, in your instruction i have to install the script not the filter, works fine now. Thank you

**Comment by jspenguin2017** [comment]
Alright. Closing then. 
Keep in mind that most of our filters won't work with Adguard.

**Comment by uBlock-user** [comment]
https://github.com/jspenguin2017/AdBlockProtector/issues/146

Please don't open duplicate issues.
