### ISSUE TITLE
gentside.com

### ISSUE THREAD

**Issue by Slowerzs** [jspenguin2017/AdBlockProtector#230]
Hi,

Test link: 
http://gaming.gentside.com/jak-and-daxter/jak-and-daxter-l-039-un-des-meilleurs-jeux-ps2-debarque-sur-ps4-cette-annee_art19381.html
Screenshot: 

Browser: 
 Chrome
AdBlocker: 
 uBlock
Script Host: 
 Tampermonkey

It is quite easy to create a filter, but the name is always changing..

**Comment by jspenguin2017** [comment]
This is now fixed. Thanks for the report.

**Comment by uBlock-user** [comment]
Filter

```
gentside.com##body > div[id]:has(:scope > img[src$="adb-arrow.png"])
gentside.com##body > div[id$="-after"]
```

**Comment by uBlock-user** [comment]
anti adblock script - http://static.gm.gtsstatic.com/static/mscripts/index_344.js

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing. Please let me know if something is not right.
