### ISSUE TITLE
flashx.tv

### ISSUE THREAD

**Issue by rayman89** [jspenguin2017/AdBlockProtector#231]
Flashxtv links do not work. Once you click on it the video doesn't play it satys as a black square.

Test link:  http://www.alluc.ee/l/The-Simpsons-S09E12-DVDRip-XviD-mp4/aw0jlrhk

I'm on Firefox 54  x64 ith ublocker origin

**Comment by uBlock-user** [comment]
Github doesn't provide any such functionality. For flashx.tv - https://github.com/jspenguin2017/AdBlockProtector/issues/130

**Comment by rayman89** [comment]
I noticed that there is somethin on the scrip of AB protector that messes up with the video if you disable the AB Protector script it works as intended.

**Comment by jspenguin2017** [comment]
It works fine with Script active. 
![image](https://cloud.githubusercontent.com/assets/7283682/26364718/79631c6e-3fa2-11e7-8649-e64eaa7419ed.png)

**Comment by rayman89** [comment]
It's on embed videos not the direct page. @jspenguin2017

**Comment by jspenguin2017** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/26364906/352cafbe-3fa3-11e7-9125-0e009b3f14ed.png)
FireFox marked as not work.

**Comment by rayman89** [comment]
So it's a firefox problem then?

**Comment by jspenguin2017** [comment]
Maybe.

**Comment by rayman89** [comment]
Taking this lines off the script makes it work though

if (a.domCmp(["flashx.tv"])) {
   a.filter("document.addEventListener", a.matchMethod.RegExp, /^(mousedown|keydown|contextmenu)$/);

cant you make them only work if the browser is chrome or not work if the browser is firefox?

**Comment by jspenguin2017** [comment]
Read the contribution guideline.
