### ISSUE TITLE
cnnturk.com

### ISSUE THREAD

**Issue by snoffer** [jspenguin2017/AdBlockProtector#923]
Test link
https://www.cnnturk.com/ekonomi/turkiye/son-dakika-enflasyon-rakamlari-aciklandi

Screenshot
https://imgur.com/a/OKGbSaZ

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://imgur.com/a/Vo4B3HN

### Environment (Required): 

- Operating System and Version: W7 SP1
- Browser and Version: Chrome 66.0.3359.139
- Adblocker and Version: Nano Adblocker v1.0.0.46
 

#### Your filter lists (Required): 
https://imgur.com/a/u8Z2qhp

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
The OP opened the [same issue](https://github.com/uBlockOrigin/uAssets/issues/2166) at `uAssets`.
The fix works on my end.
